"""ADR-044 R2.4/R2.5 — user linkage journal schema constants (DB CHECK-aligned).

Mirrors CHECK constraints on identity_reconciliation_runs.operation,
user_linkage_execute_items.action/status, and security_audit_log.event_type.
"""
from __future__ import annotations

# identity_reconciliation_runs.operation (phase='R2')
OPERATION_EXECUTE_PREVIEW = "USER_LINKAGE_EXECUTE_PREVIEW"
OPERATION_EXECUTE = "USER_LINKAGE_EXECUTE"
OPERATION_MANUAL_LINK = "USER_LINKAGE_MANUAL_LINK"
OPERATION_MANUAL_UNLINK = "USER_LINKAGE_MANUAL_UNLINK"
OPERATION_ROLLBACK_ITEM = "USER_LINKAGE_ROLLBACK_ITEM"
OPERATION_REPAIR_PREVIEW = "USER_LINKAGE_REPAIR_PREVIEW"
OPERATION_RERUN_EXECUTE = "USER_LINKAGE_RERUN_EXECUTE"

R2_RUN_OPERATIONS = frozenset(
    {
        OPERATION_EXECUTE_PREVIEW,
        OPERATION_EXECUTE,
        OPERATION_MANUAL_LINK,
        OPERATION_MANUAL_UNLINK,
        OPERATION_ROLLBACK_ITEM,
        OPERATION_REPAIR_PREVIEW,
        OPERATION_RERUN_EXECUTE,
    }
)

# user_linkage_execute_items.action
ACTION_LINK = "LINK"
ACTION_NOOP_ALREADY_LINKED = "NOOP_ALREADY_LINKED"
ACTION_SKIP_NOT_APPROVED = "SKIP_NOT_APPROVED"
ACTION_SKIP_PREVIEW_DRIFT = "SKIP_PREVIEW_DRIFT"
ACTION_SKIP_CLASSIFICATION_REGRESSION = "SKIP_CLASSIFICATION_REGRESSION"
ACTION_SKIP_EXCLUDED = "SKIP_EXCLUDED"
ACTION_FAIL_ALREADY_LINKED_DIFFERENT = "FAIL_ALREADY_LINKED_DIFFERENT"
ACTION_FAIL_EMPLOYEE_CONFLICT = "FAIL_EMPLOYEE_CONFLICT"
ACTION_MANUAL_LINK = "MANUAL_LINK"
ACTION_MANUAL_UNLINK = "MANUAL_UNLINK"
ACTION_ROLLBACK_LINK = "ROLLBACK_LINK"
ACTION_REPAIR_PREVIEW = "REPAIR_PREVIEW"
ACTION_RERUN_EXECUTE = "RERUN_EXECUTE"

EXECUTE_ITEM_ACTIONS = frozenset(
    {
        ACTION_LINK,
        ACTION_NOOP_ALREADY_LINKED,
        ACTION_SKIP_NOT_APPROVED,
        ACTION_SKIP_PREVIEW_DRIFT,
        ACTION_SKIP_CLASSIFICATION_REGRESSION,
        ACTION_SKIP_EXCLUDED,
        ACTION_FAIL_ALREADY_LINKED_DIFFERENT,
        ACTION_FAIL_EMPLOYEE_CONFLICT,
        ACTION_MANUAL_LINK,
        ACTION_MANUAL_UNLINK,
        ACTION_ROLLBACK_LINK,
        ACTION_REPAIR_PREVIEW,
        ACTION_RERUN_EXECUTE,
    }
)

# user_linkage_execute_items.status
STATUS_PLANNED = "PLANNED"
STATUS_APPLIED = "APPLIED"
STATUS_SKIPPED = "SKIPPED"
STATUS_FAILED = "FAILED"
STATUS_NOOP_ALREADY_LINKED = "NOOP_ALREADY_LINKED"
STATUS_NOOP_ALREADY_UNLINKED = "NOOP_ALREADY_UNLINKED"
STATUS_NOOP_ALREADY_ROLLED_BACK = "NOOP_ALREADY_ROLLED_BACK"

EXECUTE_ITEM_STATUSES = frozenset(
    {
        STATUS_PLANNED,
        STATUS_APPLIED,
        STATUS_SKIPPED,
        STATUS_FAILED,
        STATUS_NOOP_ALREADY_LINKED,
        STATUS_NOOP_ALREADY_UNLINKED,
        STATUS_NOOP_ALREADY_ROLLED_BACK,
    }
)

# user_linkage_execute_items.reason_codes (JSONB array; documented contract)
REASON_MANUAL_OPERATOR_DECISION = "MANUAL_OPERATOR_DECISION"
REASON_ROLLBACK_PAYLOAD_APPLIED = "ROLLBACK_PAYLOAD_APPLIED"
REASON_ROLLBACK_TARGET_CHANGED = "ROLLBACK_TARGET_CHANGED"
REASON_ROLLBACK_ALREADY_APPLIED = "ROLLBACK_ALREADY_APPLIED"
REASON_LINK_TARGET_CONFLICT = "LINK_TARGET_CONFLICT"
REASON_UNLINK_TARGET_EMPTY = "UNLINK_TARGET_EMPTY"
REASON_CONCURRENT_RUN_BLOCKED = "CONCURRENT_RUN_BLOCKED"

R2_5_REASON_CODES = frozenset(
    {
        REASON_MANUAL_OPERATOR_DECISION,
        REASON_ROLLBACK_PAYLOAD_APPLIED,
        REASON_ROLLBACK_TARGET_CHANGED,
        REASON_ROLLBACK_ALREADY_APPLIED,
        REASON_LINK_TARGET_CONFLICT,
        REASON_UNLINK_TARGET_EMPTY,
        REASON_CONCURRENT_RUN_BLOCKED,
    }
)

# identity_reconciliation_runs.status
RUN_STATUS_RUNNING = "running"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"

# security_audit_log.event_type (user linkage subset)
EVENT_USER_EMPLOYEE_LINKED = "USER_EMPLOYEE_LINKED"
EVENT_USER_EMPLOYEE_UNLINKED = "USER_EMPLOYEE_UNLINKED"
EVENT_USER_EMPLOYEE_LINK_ROLLED_BACK = "USER_EMPLOYEE_LINK_ROLLED_BACK"

USER_LINKAGE_AUDIT_EVENT_TYPES = frozenset(
    {
        EVENT_USER_EMPLOYEE_LINKED,
        EVENT_USER_EMPLOYEE_UNLINKED,
        EVENT_USER_EMPLOYEE_LINK_ROLLED_BACK,
    }
)
