"""Employee onboarding status constants (WP-ONBOARDING-001)."""
from __future__ import annotations

ONBOARDING_STATUS_PLANNED = "planned"
ONBOARDING_STATUS_ACTIVE = "active"
ONBOARDING_STATUS_COMPLETED = "completed"
ONBOARDING_STATUS_CANCELLED = "cancelled"

ONBOARDING_STATUSES: tuple[str, ...] = (
    ONBOARDING_STATUS_PLANNED,
    ONBOARDING_STATUS_ACTIVE,
    ONBOARDING_STATUS_COMPLETED,
    ONBOARDING_STATUS_CANCELLED,
)

TERMINAL_ONBOARDING_STATUSES: frozenset[str] = frozenset(
    {ONBOARDING_STATUS_COMPLETED, ONBOARDING_STATUS_CANCELLED}
)

CHECKLIST_ITEM_STATUS_PENDING = "pending"
CHECKLIST_ITEM_STATUS_COMPLETED = "completed"
CHECKLIST_ITEM_STATUS_SKIPPED = "skipped"

CHECKLIST_ITEM_STATUSES: tuple[str, ...] = (
    CHECKLIST_ITEM_STATUS_PENDING,
    CHECKLIST_ITEM_STATUS_COMPLETED,
    CHECKLIST_ITEM_STATUS_SKIPPED,
)

CHECKLIST_CODE_LNA = "lna_introduction"
CHECKLIST_CODE_PASS = "pass_issue"
CHECKLIST_CODE_EQUIPMENT = "equipment_issue"
CHECKLIST_CODE_ACCOUNTS = "account_creation"
CHECKLIST_CODE_SAFETY = "safety_briefing"
CHECKLIST_CODE_DEPARTMENT = "department_introduction"

STANDARD_CHECKLIST_CODES: tuple[str, ...] = (
    CHECKLIST_CODE_LNA,
    CHECKLIST_CODE_PASS,
    CHECKLIST_CODE_EQUIPMENT,
    CHECKLIST_CODE_ACCOUNTS,
    CHECKLIST_CODE_SAFETY,
    CHECKLIST_CODE_DEPARTMENT,
)

STANDARD_CHECKLIST_TITLES: dict[str, str] = {
    CHECKLIST_CODE_LNA: "Ознакомление с ЛНА",
    CHECKLIST_CODE_PASS: "Выдача пропуска",
    CHECKLIST_CODE_EQUIPMENT: "Выдача оборудования",
    CHECKLIST_CODE_ACCOUNTS: "Создание учётных записей",
    CHECKLIST_CODE_SAFETY: "Инструктаж по охране труда",
    CHECKLIST_CODE_DEPARTMENT: "Знакомство с подразделением",
}

DEFAULT_ONBOARDING_DURATION_DAYS = 90

# WP-ONBOARDING-002: task assignee kinds
ASSIGNEE_KIND_HR = "hr"
ASSIGNEE_KIND_MENTOR = "mentor"
ASSIGNEE_KIND_EMPLOYEE = "employee"

ASSIGNEE_KINDS: tuple[str, ...] = (
    ASSIGNEE_KIND_HR,
    ASSIGNEE_KIND_MENTOR,
    ASSIGNEE_KIND_EMPLOYEE,
)

# WP-ONBOARDING-002: task priorities
PRIORITY_LOW = "low"
PRIORITY_NORMAL = "normal"
PRIORITY_HIGH = "high"
PRIORITY_URGENT = "urgent"

TASK_PRIORITIES: tuple[str, ...] = (
    PRIORITY_LOW,
    PRIORITY_NORMAL,
    PRIORITY_HIGH,
    PRIORITY_URGENT,
)

# WP-ONBOARDING-002: notification event types
NOTIFICATION_TASK_ASSIGNED = "TASK_ASSIGNED"
NOTIFICATION_TASK_DUE_SOON = "TASK_DUE_SOON"
NOTIFICATION_TASK_OVERDUE = "TASK_OVERDUE"
NOTIFICATION_TASK_COMPLETED = "TASK_COMPLETED"

ONBOARDING_NOTIFICATION_TYPES: tuple[str, ...] = (
    NOTIFICATION_TASK_ASSIGNED,
    NOTIFICATION_TASK_DUE_SOON,
    NOTIFICATION_TASK_OVERDUE,
    NOTIFICATION_TASK_COMPLETED,
)

# Default assignee per standard checklist code
DEFAULT_ASSIGNEE_BY_CHECKLIST_CODE: dict[str, str] = {
    CHECKLIST_CODE_DEPARTMENT: ASSIGNEE_KIND_MENTOR,
}

DEFAULT_ASSIGNEE_KIND = ASSIGNEE_KIND_HR


def is_terminal_onboarding_status(status: str) -> bool:
    return status in TERMINAL_ONBOARDING_STATUSES


def is_onboarding_editable(status: str) -> bool:
    return not is_terminal_onboarding_status(status)
