"""Incoming Information domain constants."""
from __future__ import annotations

ACCESS_LEVEL_NORMAL = "NORMAL"
ACCESS_LEVEL_RESTRICTED = "RESTRICTED"
ACCESS_LEVELS: tuple[str, ...] = (ACCESS_LEVEL_NORMAL, ACCESS_LEVEL_RESTRICTED)

SENDER_KIND_EXTERNAL_TEXT = "EXTERNAL_TEXT"
SENDER_KIND_PERSON = "PERSON"
SENDER_KIND_EMPLOYEE = "EMPLOYEE"
SENDER_KIND_ORG_UNIT = "ORG_UNIT"
SENDER_KINDS: tuple[str, ...] = (
    SENDER_KIND_EXTERNAL_TEXT,
    SENDER_KIND_PERSON,
    SENDER_KIND_EMPLOYEE,
    SENDER_KIND_ORG_UNIT,
)

ADDRESSEE_KIND_TEXT = "TEXT"
ADDRESSEE_KIND_USER = "USER"
ADDRESSEE_KIND_EMPLOYEE = "EMPLOYEE"
ADDRESSEE_KIND_ORG_UNIT = "ORG_UNIT"
ADDRESSEE_KIND_POSITION = "POSITION"
ADDRESSEE_KINDS: tuple[str, ...] = (
    ADDRESSEE_KIND_TEXT,
    ADDRESSEE_KIND_USER,
    ADDRESSEE_KIND_EMPLOYEE,
    ADDRESSEE_KIND_ORG_UNIT,
    ADDRESSEE_KIND_POSITION,
)

ASSIGNMENT_ROLE_PRIMARY = "PRIMARY"
ASSIGNMENT_ROLE_COEXECUTOR = "COEXECUTOR"
ASSIGNMENT_ROLES: tuple[str, ...] = (ASSIGNMENT_ROLE_PRIMARY, ASSIGNMENT_ROLE_COEXECUTOR)

ASSIGNMENT_CANCEL_REASON_TRANSFER = "TRANSFER"
ASSIGNMENT_CANCEL_REASON_REASSIGN = "REASSIGN"

STATUS_REGISTERED = "REGISTERED"
STATUS_ASSIGNED = "ASSIGNED"
STATUS_IN_PROGRESS = "IN_PROGRESS"
STATUS_WAITING_INFORMATION = "WAITING_INFORMATION"
STATUS_RESOLVED = "RESOLVED"
STATUS_CLOSED = "CLOSED"
STATUS_TRANSFERRED = "TRANSFERRED"
STATUS_CANCELLED = "CANCELLED"

# Legacy codes kept for migration compatibility only.
STATUS_UNDER_REVIEW = "UNDER_REVIEW"
STATUS_EXECUTOR_ASSIGNED = "EXECUTOR_ASSIGNED"
STATUS_AWAITING_INFO = "AWAITING_INFO"
STATUS_DRAFT_PREPARED = "DRAFT_PREPARED"
STATUS_ON_APPROVAL = "ON_APPROVAL"
STATUS_EXECUTED = "EXECUTED"

TERMINAL_STATUS_CODES: frozenset[str] = frozenset(
    {
        STATUS_CLOSED,
        STATUS_TRANSFERRED,
        STATUS_CANCELLED,
    }
)

INITIAL_STATUS_CODE = STATUS_REGISTERED

TRANSFER_SCOPE_INTERNAL = "INTERNAL"
TRANSFER_SCOPE_EXTERNAL = "EXTERNAL"
TRANSFER_SCOPES: tuple[str, ...] = (TRANSFER_SCOPE_INTERNAL, TRANSFER_SCOPE_EXTERNAL)

RECIPIENT_KIND_USER = "USER"
RECIPIENT_KIND_ORG_UNIT = "ORG_UNIT"
RECIPIENT_KIND_TEXT = "TEXT"
RECIPIENT_KINDS: tuple[str, ...] = (RECIPIENT_KIND_USER, RECIPIENT_KIND_ORG_UNIT, RECIPIENT_KIND_TEXT)

AUDIT_ACTION_CREATED = "CREATED"
AUDIT_ACTION_FIELD_CHANGED = "FIELD_CHANGED"
AUDIT_ACTION_STATUS_CHANGED = "STATUS_CHANGED"
AUDIT_ACTION_ASSIGNMENT_CHANGED = "ASSIGNMENT_CHANGED"
AUDIT_ACTION_LINK_ADDED = "LINK_ADDED"
AUDIT_ACTION_LINK_REMOVED = "LINK_REMOVED"
AUDIT_ACTION_ATTACHMENT_ADDED = "ATTACHMENT_ADDED"
AUDIT_ACTION_ATTACHMENT_REMOVED = "ATTACHMENT_REMOVED"
AUDIT_ACTION_OPERATION_ASSIGN = "OPERATION_ASSIGN"
AUDIT_ACTION_OPERATION_REASSIGN = "OPERATION_REASSIGN"
AUDIT_ACTION_OPERATION_TRANSFER = "OPERATION_TRANSFER"
AUDIT_ACTION_OPERATION_START = "OPERATION_START"
AUDIT_ACTION_OPERATION_WAIT = "OPERATION_WAIT"
AUDIT_ACTION_OPERATION_RESUME = "OPERATION_RESUME"
AUDIT_ACTION_OPERATION_CHANGE_DEADLINE = "OPERATION_CHANGE_DEADLINE"
AUDIT_ACTION_OPERATION_RESOLVE = "OPERATION_RESOLVE"
AUDIT_ACTION_OPERATION_CLOSE = "OPERATION_CLOSE"
AUDIT_ACTION_OPERATION_REOPEN = "OPERATION_REOPEN"
AUDIT_ACTION_OPERATION_CANCEL = "OPERATION_CANCEL"

LINK_TYPE_BASIS = "BASIS"
LINK_TYPE_RESULT = "RESULT"
LINK_TYPE_DISCIPLINARY = "DISCIPLINARY"
LINK_TYPE_OTHER = "OTHER"


def is_terminal_status_code(code: str) -> bool:
    return code in TERMINAL_STATUS_CODES


def terminal_status_codes_for_guard() -> tuple[str, ...]:
    return tuple(sorted(TERMINAL_STATUS_CODES))
