"""Lifecycle audit action constants (WP-PPR-APPLICANT-004)."""
from __future__ import annotations

LIFECYCLE_ACTION_REGISTERED = "registered"
LIFECYCLE_ACTION_INTAKE_LINK_ISSUED = "intake_link_issued"
LIFECYCLE_ACTION_INTAKE_OPENED = "intake_opened"
LIFECYCLE_ACTION_INTAKE_SUBMITTED = "intake_submitted"
LIFECYCLE_ACTION_INTAKE_EDITED_ON_BEHALF = "intake_edited_on_behalf"
LIFECYCLE_ACTION_REVIEW_STARTED = "review_started"
LIFECYCLE_ACTION_REVIEW_COMPLETED = "review_completed"
LIFECYCLE_ACTION_INTAKE_TRANSFERRED = "intake_transferred"
LIFECYCLE_ACTION_RESOLUTION_OPENED = "resolution_opened"
LIFECYCLE_ACTION_RESOLUTION_RECORDED = "resolution_recorded"
LIFECYCLE_ACTION_RESOLUTION_CHANGED = "resolution_changed"
LIFECYCLE_ACTION_RESOLUTION_REOPENED = "resolution_reopened"
LIFECYCLE_ACTION_HIRE_ORDER_DRAFT_CREATED = "hire_order_draft_created"
LIFECYCLE_ACTION_HIRE_APPLIED = "hire_applied"
LIFECYCLE_ACTION_COMPLETED = "completed"
LIFECYCLE_ACTION_REJECTED = "rejected"
LIFECYCLE_ACTION_CANCELLED = "cancelled"
LIFECYCLE_ACTION_EXPIRED = "expired"

LIFECYCLE_AUDIT_ACTIONS: tuple[str, ...] = (
    LIFECYCLE_ACTION_REGISTERED,
    LIFECYCLE_ACTION_INTAKE_LINK_ISSUED,
    LIFECYCLE_ACTION_INTAKE_OPENED,
    LIFECYCLE_ACTION_INTAKE_SUBMITTED,
    LIFECYCLE_ACTION_INTAKE_EDITED_ON_BEHALF,
    LIFECYCLE_ACTION_REVIEW_STARTED,
    LIFECYCLE_ACTION_REVIEW_COMPLETED,
    LIFECYCLE_ACTION_INTAKE_TRANSFERRED,
    LIFECYCLE_ACTION_RESOLUTION_OPENED,
    LIFECYCLE_ACTION_RESOLUTION_RECORDED,
    LIFECYCLE_ACTION_RESOLUTION_CHANGED,
    LIFECYCLE_ACTION_RESOLUTION_REOPENED,
    LIFECYCLE_ACTION_HIRE_ORDER_DRAFT_CREATED,
    LIFECYCLE_ACTION_HIRE_APPLIED,
    LIFECYCLE_ACTION_COMPLETED,
    LIFECYCLE_ACTION_REJECTED,
    LIFECYCLE_ACTION_CANCELLED,
    LIFECYCLE_ACTION_EXPIRED,
)

JOURNAL_VIEW_ACTIVE = "active"
JOURNAL_VIEW_ARCHIVE = "archive"
JOURNAL_VIEWS: frozenset[str] = frozenset({JOURNAL_VIEW_ACTIVE, JOURNAL_VIEW_ARCHIVE})
