"""Director resolution workflow constants (WP-PPR-APPLICANT-002)."""
from __future__ import annotations

RESOLUTION_ACTION_OPENED = "opened"
RESOLUTION_ACTION_RECORDED = "recorded"
RESOLUTION_ACTION_CHANGED = "changed"
RESOLUTION_ACTION_REOPENED = "reopened"

RESOLUTION_ACTIONS: tuple[str, ...] = (
    RESOLUTION_ACTION_OPENED,
    RESOLUTION_ACTION_RECORDED,
    RESOLUTION_ACTION_CHANGED,
    RESOLUTION_ACTION_REOPENED,
)

RESOLUTION_OUTCOME_APPROVED = "approved"
RESOLUTION_OUTCOME_REJECTED = "rejected"
RESOLUTION_OUTCOME_REVISION_REQUESTED = "revision_requested"

RESOLUTION_OUTCOMES: tuple[str, ...] = (
    RESOLUTION_OUTCOME_APPROVED,
    RESOLUTION_OUTCOME_REJECTED,
    RESOLUTION_OUTCOME_REVISION_REQUESTED,
)

RESOLUTION_OUTCOMES_REQUIRING_COMMENT: frozenset[str] = frozenset(
    {
        RESOLUTION_OUTCOME_REJECTED,
        RESOLUTION_OUTCOME_REVISION_REQUESTED,
    }
)
