"""Personnel Application lifecycle status constants and predicates (ADR-057, 001A §6)."""
from __future__ import annotations

APPLICATION_STATUS_REGISTERED = "registered"
APPLICATION_STATUS_INTAKE_PENDING = "intake_pending"
APPLICATION_STATUS_INTAKE_SUBMITTED = "intake_submitted"
APPLICATION_STATUS_UNDER_REVIEW = "under_review"
APPLICATION_STATUS_REVIEW_COMPLETED = "review_completed"
APPLICATION_STATUS_RESOLUTION_PENDING = "resolution_pending"
APPLICATION_STATUS_APPROVED = "approved"
APPLICATION_STATUS_REJECTED = "rejected"
APPLICATION_STATUS_REVISION_REQUESTED = "revision_requested"
APPLICATION_STATUS_ORDER_DRAFT_CREATED = "order_draft_created"
APPLICATION_STATUS_AWAITING_DIRECTOR_RESOLUTION = "awaiting_director_resolution"
APPLICATION_STATUS_RESOLUTION_APPROVED = "resolution_approved"
APPLICATION_STATUS_RESOLUTION_REJECTED = "resolution_rejected"
APPLICATION_STATUS_COMPLETED = "completed"
APPLICATION_STATUS_WITHDRAWN = "withdrawn"
APPLICATION_STATUS_CANCELLED = "cancelled"
APPLICATION_STATUS_EXPIRED = "expired"

APPLICATION_STATUSES: tuple[str, ...] = (
    APPLICATION_STATUS_REGISTERED,
    APPLICATION_STATUS_INTAKE_PENDING,
    APPLICATION_STATUS_INTAKE_SUBMITTED,
    APPLICATION_STATUS_UNDER_REVIEW,
    APPLICATION_STATUS_REVIEW_COMPLETED,
    APPLICATION_STATUS_RESOLUTION_PENDING,
    APPLICATION_STATUS_APPROVED,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_REVISION_REQUESTED,
    APPLICATION_STATUS_ORDER_DRAFT_CREATED,
    APPLICATION_STATUS_AWAITING_DIRECTOR_RESOLUTION,
    APPLICATION_STATUS_RESOLUTION_APPROVED,
    APPLICATION_STATUS_RESOLUTION_REJECTED,
    APPLICATION_STATUS_COMPLETED,
    APPLICATION_STATUS_WITHDRAWN,
    APPLICATION_STATUS_CANCELLED,
    APPLICATION_STATUS_EXPIRED,
)

TERMINAL_APPLICATION_STATUSES: frozenset[str] = frozenset(
    {
        APPLICATION_STATUS_COMPLETED,
        APPLICATION_STATUS_WITHDRAWN,
        APPLICATION_STATUS_CANCELLED,
        APPLICATION_STATUS_RESOLUTION_REJECTED,
        APPLICATION_STATUS_REJECTED,
        APPLICATION_STATUS_EXPIRED,
    }
)

APPLICATION_SOURCE_PAPER = "paper"
APPLICATION_SOURCES: tuple[str, ...] = (APPLICATION_SOURCE_PAPER,)

VACANCY_CHECK_PENDING = "pending"
VACANCY_CHECK_CONFIRMED_VISUALLY = "confirmed_visually"
VACANCY_CHECK_NOT_CONFIRMED = "not_confirmed"
VACANCY_CHECK_STATUSES: tuple[str, ...] = (
    VACANCY_CHECK_PENDING,
    VACANCY_CHECK_CONFIRMED_VISUALLY,
    VACANCY_CHECK_NOT_CONFIRMED,
)

DIRECTOR_RESOLUTION_PENDING = "pending"
DIRECTOR_RESOLUTION_APPROVED = "approved"
DIRECTOR_RESOLUTION_REJECTED = "rejected"
DIRECTOR_RESOLUTION_REVISION_REQUESTED = "revision_requested"
DIRECTOR_RESOLUTION_STATUSES: tuple[str, ...] = (
    DIRECTOR_RESOLUTION_PENDING,
    DIRECTOR_RESOLUTION_APPROVED,
    DIRECTOR_RESOLUTION_REJECTED,
    DIRECTOR_RESOLUTION_REVISION_REQUESTED,
)

REGISTRATION_INITIAL_STATUS = APPLICATION_STATUS_REGISTERED


def is_terminal_application_status(status: str) -> bool:
    return status in TERMINAL_APPLICATION_STATUSES


def is_active_application_status(status: str) -> bool:
    return not is_terminal_application_status(status)


def terminal_statuses_for_partial_index() -> tuple[str, ...]:
    """Canonical terminal set — must stay synchronized with Alembic partial index."""
    return tuple(sorted(TERMINAL_APPLICATION_STATUSES))
