import type { DocumentDetail, WorkspaceDetail } from "./types";

export function baseWorkspaceDetail(overrides: Partial<WorkspaceDetail> = {}): WorkspaceDetail {
  return {
    workspace: {
      workspace_id: 1,
      organization_id: 1,
      drafting_path: "SUBMITTED_TEXT",
      stage: "TRANSLATION_IN_PROGRESS",
      submitting_org_unit_id: 10,
      record_creator_user_id: 100,
      content_author_reference: "200",
      content_author_type: "PERSON",
      proposed_title: "Test order",
      submitted_at: "2026-01-01T10:00:00Z",
      accepted_at: "2026-01-02T10:00:00Z",
      created_at: "2026-01-01T10:00:00Z",
      updated_at: "2026-01-03T10:00:00Z",
      version: 5,
      document_id: null,
    },
    blocks: [
      {
        block_id: 1,
        workspace_id: 1,
        locale: "ru",
        block_type: "BODY",
        submitted_text: "RU text",
        workspace_effective_text: "RU text",
        sequence: 1,
        source_type: "SUBMISSION",
        review_state: "ACCEPTED",
        version: 2,
        created_at: "2026-01-01T10:00:00Z",
        updated_at: "2026-01-02T10:00:00Z",
      },
      {
        block_id: 2,
        workspace_id: 1,
        locale: "kk",
        block_type: "BODY",
        submitted_text: "KK text",
        workspace_effective_text: "KK text",
        sequence: 1,
        source_type: "SUBMISSION",
        review_state: "ACCEPTED",
        version: 1,
        created_at: "2026-01-01T10:00:00Z",
        updated_at: "2026-01-02T10:00:00Z",
      },
    ],
    provenance: [],
    clarifications: [],
    audit: [],
    validation: { is_valid: true, has_errors: false, has_warnings: false, issues: [] },
    locale_completeness: { ru_present: true, kk_present: true, locales_present: ["ru", "kk"] },
    readiness_for_editorial: true,
    readiness_for_editorial_package: false,
    translation_assignments: [],
    content_confirmations: [],
    bilingual_reconciliations: [],
    ...overrides,
  };
}

export function baseDocumentDetail(overrides: Partial<DocumentDetail> = {}): DocumentDetail {
  return {
    document: {
      document_id: 42,
      workspace_id: 1,
      document_kind: "OPERATIONAL_ORDER",
      status: "CREATED",
      created_from_workspace_version: 8,
      created_from_workspace_fingerprint: "abc123def4567890",
      promotion_id: 1,
      created_at: "2026-01-10T10:00:00Z",
      created_by_user_id: 100,
      version: 1,
      submitting_org_unit_id: 10,
      ready_for_signature_at: null,
      ready_for_signature_by_user_id: null,
    },
    current_version: {
      id: 1,
      document_id: 42,
      version_number: 1,
      workspace_version: 8,
      promotion_snapshot_version: 1,
      snapshot_fingerprint: "a91f1234567890e42c",
      is_current: true,
      created_at: "2026-01-10T10:00:00Z",
      created_by_user_id: 100,
    },
    signing_authority: null,
    readiness_validation: null,
    latest_lifecycle_transition: null,
    org_scope_source: { workspace_id: 1, submitting_org_unit_id: 10 },
    promotion: {
      id: 1,
      workspace_id: 1,
      document_id: 42,
      status: "COMPLETED",
      workspace_version: 8,
      workspace_fingerprint: "abc123def4567890",
      snapshot_fingerprint: "a91f1234567890e42c",
      snapshot_version: 1,
      promoted_by_user_id: 100,
      promoted_at: "2026-01-10T10:00:00Z",
      created_at: "2026-01-10T10:00:00Z",
    },
    revision_recommended: false,
    workspace_drift_detected: false,
    ...overrides,
  };
}
