"""Corpsite SQLAlchemy ORM models."""
from app.db.base import Base
from app.db.models.aliases import OrgUnitAlias, PositionAlias
from app.db.models.employee_identity import IDENTITY_TYPE_IIN, EmployeeIdentity
from app.db.models.hr_import import (
    BATCH_STATUS_APPLIED,
    BATCH_STATUS_APPLY_PENDING,
    BATCH_STATUS_CANCELLED,
    BATCH_STATUS_FAILED,
    BATCH_STATUS_IN_REVIEW,
    BATCH_STATUS_PARSED,
    BATCH_STATUS_PARTIALLY_APPLIED,
    BATCH_STATUS_UPLOADED,
    HrImportBatch,
    HrImportDocumentCandidate,
    HrImportRow,
    MATCH_STATUS_AUTO,
    MATCH_STATUS_INVALID,
    MATCH_STATUS_NO_MATCH,
    MATCH_STATUS_REVIEW,
    MATCH_STATUS_SKIPPED,
    REVIEW_STATUS_APPROVED,
    REVIEW_STATUS_MERGED,
    REVIEW_STATUS_PENDING,
    REVIEW_STATUS_REJECTED,
    SOURCE_TYPE_HR_CONTROL_LIST,
)

__all__ = [
    "Base",
    "EmployeeIdentity",
    "HrImportBatch",
    "HrImportDocumentCandidate",
    "HrImportRow",
    "IDENTITY_TYPE_IIN",
    "OrgUnitAlias",
    "PositionAlias",
    "SOURCE_TYPE_HR_CONTROL_LIST",
    "BATCH_STATUS_UPLOADED",
    "BATCH_STATUS_PARSED",
    "BATCH_STATUS_IN_REVIEW",
    "BATCH_STATUS_APPLY_PENDING",
    "BATCH_STATUS_APPLIED",
    "BATCH_STATUS_PARTIALLY_APPLIED",
    "BATCH_STATUS_FAILED",
    "BATCH_STATUS_CANCELLED",
    "MATCH_STATUS_AUTO",
    "MATCH_STATUS_REVIEW",
    "MATCH_STATUS_NO_MATCH",
    "MATCH_STATUS_INVALID",
    "MATCH_STATUS_SKIPPED",
    "REVIEW_STATUS_PENDING",
    "REVIEW_STATUS_APPROVED",
    "REVIEW_STATUS_REJECTED",
    "REVIEW_STATUS_MERGED",
]
