"""Department recoding — map import Excel department names to org_units."""
from __future__ import annotations

DEPARTMENT_GROUP_CLINICAL = "CLINICAL"
DEPARTMENT_GROUP_PARACLINICAL = "PARACLINICAL"
DEPARTMENT_GROUP_ADMINISTRATIVE = "ADMINISTRATIVE"

DEPARTMENT_GROUPS = (
    DEPARTMENT_GROUP_CLINICAL,
    DEPARTMENT_GROUP_PARACLINICAL,
    DEPARTMENT_GROUP_ADMINISTRATIVE,
)
