"""ORM constants for HR Baseline and PublicationOrigin."""
from __future__ import annotations

SOURCE_TYPE_HR_CONTROL_LIST = "HR_CONTROL_LIST"

BASELINE_DELETION_SOFT = "SOFT"
BASELINE_DELETION_HARD = "HARD"

BATCH_DIFF_STATUS_NOT_COMPUTED = "NOT_COMPUTED"
BATCH_DIFF_STATUS_STALE = "STALE"
BATCH_DIFF_STATUS_CURRENT = "CURRENT"
