"""Constants for personnel order editorial generation (WP-PO-EDIT-002)."""
from __future__ import annotations

from app.db.models.personnel_orders import (
    BASIS_TYPE_COMMISSION_PROTOCOL,
    BASIS_TYPE_COURT_ACT,
    BASIS_TYPE_MANAGEMENT_SUBMISSION,
    BASIS_TYPE_MEDICAL_CONCLUSION,
    BASIS_TYPE_MEMO,
    BASIS_TYPE_OTHER,
    BASIS_TYPE_PERSONAL_APPLICATION,
    BASIS_TYPES,
    ITEM_BLOCK_TYPE_BASIS,
    ITEM_BLOCK_TYPE_BODY,
    ITEM_BLOCK_TYPES,
    LOCALE_KK,
    LOCALE_RU,
    ORDER_BLOCK_TYPE_CLOSING,
    ORDER_BLOCK_TYPE_PREAMBLE,
    ORDER_BLOCK_TYPE_TITLE,
    ORDER_BLOCK_TYPES,
    REVIEW_STATUS_CURRENT,
    REVIEW_STATUS_GENERATION_FAILED,
    REVIEW_STATUS_REVIEW_REQUIRED,
    REVIEW_STATUS_STALE,
    REVIEW_STATUSES,
)

ALLOWED_LOCALES = (LOCALE_KK, LOCALE_RU)

GENERATOR_VERSION = "1.0.0"

GENERATOR_KEY_ORDER_TITLE = "order.title"
GENERATOR_KEY_ORDER_PREAMBLE = "order.preamble"
GENERATOR_KEY_ORDER_CLOSING = "order.closing"
GENERATOR_KEY_ITEM_BODY = "item.body"
GENERATOR_KEY_ITEM_BASIS = "item.basis"

__all__ = [
    "ALLOWED_LOCALES",
    "BASIS_TYPE_COMMISSION_PROTOCOL",
    "BASIS_TYPE_COURT_ACT",
    "BASIS_TYPE_MANAGEMENT_SUBMISSION",
    "BASIS_TYPE_MEDICAL_CONCLUSION",
    "BASIS_TYPE_MEMO",
    "BASIS_TYPE_OTHER",
    "BASIS_TYPE_PERSONAL_APPLICATION",
    "BASIS_TYPES",
    "GENERATOR_KEY_ITEM_BASIS",
    "GENERATOR_KEY_ITEM_BODY",
    "GENERATOR_KEY_ORDER_CLOSING",
    "GENERATOR_KEY_ORDER_PREAMBLE",
    "GENERATOR_KEY_ORDER_TITLE",
    "GENERATOR_VERSION",
    "ITEM_BLOCK_TYPE_BASIS",
    "ITEM_BLOCK_TYPE_BODY",
    "ITEM_BLOCK_TYPES",
    "ORDER_BLOCK_TYPE_CLOSING",
    "ORDER_BLOCK_TYPE_PREAMBLE",
    "ORDER_BLOCK_TYPE_TITLE",
    "ORDER_BLOCK_TYPES",
    "REVIEW_STATUS_CURRENT",
    "REVIEW_STATUS_GENERATION_FAILED",
    "REVIEW_STATUS_REVIEW_REQUIRED",
    "REVIEW_STATUS_STALE",
    "REVIEW_STATUSES",
]
