"""Focused production-shape tests for s2t3u4v5w6x."""
from __future__ import annotations

from contextlib import contextmanager
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, text

from app.db.engine import engine


MIGRATION_PATH = (
    Path(__file__).resolve().parents[1]
    / "alembic"
    / "versions"
    / "s2t3u4v5w6x_seed_org_units_general_it_transfuse.py"
)


def _migration_module():
    spec = spec_from_file_location("seed_org_units_general_it_transfuse", MIGRATION_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load migration from {MIGRATION_PATH}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


@contextmanager
def _ephemeral_database():
    db_name = f"corpsite_s2_units_{uuid4().hex[:12]}"
    admin_url = str(engine.url.render_as_string(hide_password=False)).rsplit("/", 1)[0] + "/postgres"
    test_url = admin_url.rsplit("/", 1)[0] + f"/{db_name}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    test_engine = create_engine(test_url)

    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))

    try:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE public.org_units (
                        unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                        name TEXT NOT NULL,
                        code TEXT NOT NULL UNIQUE,
                        parent_unit_id BIGINT NULL REFERENCES public.org_units(unit_id),
                        is_active BOOLEAN NOT NULL,
                        group_id BIGINT NULL
                    );

                    INSERT INTO public.org_units
                        (unit_id, name, code, parent_unit_id, is_active, group_id)
                    VALUES
                        (1, 'Корень', 'mmc_root', NULL, TRUE, NULL),
                        (60, 'Диспансер', 'DISP', 1, TRUE, 1),
                        (79, 'Администрация', 'ADMIN', 1, TRUE, 3),
                        (80, 'Выписка', 'DISCHARGE_INPUT_SEC', 1, TRUE, 3),
                        (81, 'Секция ЭРОБ', 'EROB_SEC', 1, TRUE, 1);
                    """
                )
            )
        yield test_engine
    finally:
        test_engine.dispose()
        with admin_engine.connect() as conn:
            conn.execute(
                text(
                    """
                    SELECT pg_terminate_backend(pid)
                    FROM pg_stat_activity
                    WHERE datname = :db_name AND pid <> pg_backend_pid()
                    """
                ),
                {"db_name": db_name},
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
        admin_engine.dispose()


def _run(conn, operation: str) -> None:
    migration = _migration_module()
    with Operations.context(MigrationContext.configure(conn)):
        getattr(migration, operation)()


def test_sql_contract_uses_production_columns_and_identity(monkeypatch) -> None:
    migration = _migration_module()
    upgrade_statements: list[str] = []
    downgrade_statements: list[str] = []

    monkeypatch.setattr(migration.op, "execute", upgrade_statements.append)
    migration.upgrade()
    monkeypatch.setattr(migration.op, "execute", downgrade_statements.append)
    migration.downgrade()

    assert migration.down_revision == "r1s2t3u4v5w6"
    assert len(upgrade_statements) == 1
    upgrade_sql = upgrade_statements[0]
    assert "(name, code, parent_unit_id, group_id, is_active)" in upgrade_sql
    assert "unit_id IN (79, 80, 81)" not in upgrade_sql
    assert "name_ru" not in upgrade_sql
    assert "deps_group" not in upgrade_sql
    assert "setval" not in upgrade_sql

    assert len(downgrade_statements) == 1
    downgrade_sql = downgrade_statements[0]
    assert "name_ru" not in downgrade_sql
    assert "CASCADE" not in downgrade_sql.upper()
    assert "unit_id = 79" not in downgrade_sql
    assert "unit_id = 80" not in downgrade_sql
    assert "unit_id = 81" not in downgrade_sql


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_uses_identity_and_disp_parent_with_occupied_legacy_ids() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            columns = set(
                conn.execute(
                    text(
                        """
                        SELECT column_name
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'org_units'
                        """
                    )
                ).scalars()
            )
            assert columns == {
                "unit_id",
                "name",
                "code",
                "parent_unit_id",
                "is_active",
                "group_id",
            }

            _run(conn, "upgrade")
            rows = {
                row.code: row
                for row in conn.execute(
                    text(
                        """
                        SELECT unit_id, name, code, parent_unit_id, group_id, is_active
                        FROM public.org_units
                        WHERE code IN ('GENERAL', 'IT', 'TRANSFUSE')
                        """
                    )
                ).all()
            }

            assert set(rows) == {"GENERAL", "IT", "TRANSFUSE"}
            assert {row.unit_id for row in rows.values()}.isdisjoint({79, 80, 81})
            assert all(row.unit_id >= 1000 for row in rows.values())
            assert rows["GENERAL"].name == "Общебольничный"
            assert rows["IT"].name == "IT бөлімі"
            assert rows["TRANSFUSE"].name == "Трансфузиология"
            assert [rows[code].parent_unit_id for code in ("GENERAL", "IT", "TRANSFUSE")] == [
                1,
                1,
                1,
            ]
            assert [rows[code].group_id for code in ("GENERAL", "IT", "TRANSFUSE")] == [3, 3, 2]
            assert all(row.is_active is True for row in rows.values())

            # These are the code/name/parent/group values consumed by the following t3 migration.
            assert (
                rows["TRANSFUSE"].code,
                rows["TRANSFUSE"].name,
                rows["TRANSFUSE"].parent_unit_id,
                rows["TRANSFUSE"].group_id,
            ) == ("TRANSFUSE", "Трансфузиология", 1, 2)


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_target_code_conflict_rolls_back_entire_upgrade() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units (name, code, parent_unit_id, is_active, group_id)
                    VALUES ('Чужое подразделение', 'TRANSFUSE', 1, TRUE, 3)
                    """
                )
            )

        with test_engine.connect() as conn:
            transaction = conn.begin()
            with pytest.raises(Exception, match="target code is already occupied"):
                _run(conn, "upgrade")
            transaction.rollback()

        with test_engine.connect() as conn:
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.org_units WHERE code = 'GENERAL'")
            ).scalar_one() == 0
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.org_units WHERE code = 'IT'")
            ).scalar_one() == 0
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.org_units WHERE code = 'TRANSFUSE'")
            ).scalar_one() == 1


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_downgrade_removes_only_exact_seed_rows_without_cascade() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            _run(conn, "upgrade")
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units (name, code, parent_unit_id, is_active, group_id)
                    VALUES
                        ('Общебольничный', 'GENERAL_COPY', 1, TRUE, 3),
                        ('IT бөлімі', 'IT_COPY', 1, TRUE, 3),
                        ('Трансфузиология', 'TRANSFUSE_COPY', 1, TRUE, 2)
                    """
                )
            )
            _run(conn, "downgrade")

            assert conn.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.org_units
                    WHERE code IN ('GENERAL', 'IT', 'TRANSFUSE')
                    """
                )
            ).scalar_one() == 0
            assert conn.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.org_units
                    WHERE code IN ('GENERAL_COPY', 'IT_COPY', 'TRANSFUSE_COPY')
                    """
                )
            ).scalar_one() == 3
            assert conn.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.org_units
                    WHERE unit_id IN (79, 80, 81)
                    """
                )
            ).scalar_one() == 3
