"""Focused tests for t3u4v5w6x7y reference-data migration."""
from __future__ import annotations

from contextlib import contextmanager
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, text

from app.db.engine import engine
from tests.alembic_test_helpers import alembic_config


REVISION = "t3u4v5w6x7y"
PREVIOUS_REVISION = "s2t3u4v5w6x"
MIGRATION_FILE = (
    Path(__file__).resolve().parents[1]
    / "alembic"
    / "versions"
    / "t3u4v5w6x7y_reference_positions_org_units.py"
)
S2_MIGRATION_FILE = (
    Path(__file__).resolve().parents[1]
    / "alembic"
    / "versions"
    / "s2t3u4v5w6x_seed_org_units_general_it_transfuse.py"
)

EXPECTED_POSITIONS = {
    "Инженер": "technical",
    "Заведующий отделением": "other",
    "Машинист по стирке белья": "technical",
    "Социальный работник": "medical",
    "Медицинский статистик": "medical",
    "Техник": "technical",
    "Заведующий ОТ и ТБ": "leaders",
    "Санитар по транспортировке пациентов": "medical",
    "Врач-эксперт": "medical",
    "Руководитель административно-хозяйственной службы": "leaders",
    "Буфетчица": "technical",
    "Бухгалтер-экономист": "admin",
    "Руководитель отдела": "leaders",
    "Старший ординатор": "medical",
    "Комплаенс-офицер": "admin",
    "Главный инженер": "technical",
}


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


def _migration_module(path: Path = MIGRATION_FILE):
    spec = spec_from_file_location(f"migration_{path.stem}", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load migration from {path}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@contextmanager
def _ephemeral_database(*, root_code: str = "mmc_root", seed_exact_units: bool = False):
    db_name = f"corpsite_ref_seed_{uuid4().hex[:12]}"
    admin_url = str(engine.url.render_as_string(hide_password=False)).rsplit("/", 1)[0] + "/postgres"
    test_url = admin_url.rsplit("/", 1)[0] + f"/{db_name}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    test_engine = create_engine(test_url)

    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))

    try:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE public.positions (
                        position_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
                        name TEXT NOT NULL,
                        category VARCHAR NULL
                    );
                    CREATE TABLE public.org_units (
                        unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2000) PRIMARY KEY,
                        name TEXT NOT NULL,
                        code TEXT NOT NULL UNIQUE,
                        parent_unit_id BIGINT NULL REFERENCES public.org_units(unit_id),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        group_id BIGINT NULL
                    );
                    CREATE TABLE public.employees (
                        employee_id BIGINT PRIMARY KEY,
                        position_id BIGINT NOT NULL REFERENCES public.positions(position_id),
                        org_unit_id BIGINT NOT NULL REFERENCES public.org_units(unit_id)
                    );
                    CREATE TABLE public.person_assignments (
                        assignment_id BIGINT PRIMARY KEY,
                        position_id BIGINT NOT NULL REFERENCES public.positions(position_id),
                        org_unit_id BIGINT NOT NULL REFERENCES public.org_units(unit_id)
                    );
                    """
                )
            )
            conn.execute(
                text(
                    """
                    INSERT INTO public.positions (position_id, name, category)
                    VALUES
                        (501, 'Инженер', 'technical'),
                        (502, 'инженер', 'technical'),
                        (900, 'Базовая должность', 'other');
                    """
                )
            )
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units
                        (unit_id, name, code, parent_unit_id, group_id, is_active)
                    VALUES
                        (1, 'Организация', :root_code, NULL, NULL, TRUE),
                        (60, 'Диспансер', 'DISP', 1, 1, TRUE),
                        (79, 'Администрация', 'ADMIN', 1, 3, TRUE),
                        (80, 'Выписка', 'DISCHARGE_INPUT_SEC', 1, 3, TRUE),
                        (81, 'Секция ЭРОБ', 'EROB_SEC', 1, 1, TRUE)
                    """
                ),
                {"root_code": root_code},
            )
            if seed_exact_units:
                conn.execute(
                    text(
                        """
                        INSERT INTO public.org_units
                            (unit_id, name, code, parent_unit_id, group_id, is_active)
                        VALUES
                            (3003, 'Трансфузиология', 'TRANSFUSE', 1, 2, TRUE),
                            (3004, 'Секция амбулаторной химиотерапии', 'Amb_chem', 60, 1, TRUE),
                            (3005, 'Комплаенс', 'COMPL', 1, 3, TRUE)
                        """
                    )
                )
            conn.execute(
                text(
                    """
                    INSERT INTO public.employees (employee_id, position_id, org_unit_id)
                    VALUES (1, 900, 1);
                    INSERT INTO public.person_assignments (assignment_id, position_id, org_unit_id)
                    VALUES (1, 900, 1)
                    """
                )
            )
        yield test_engine
    finally:
        test_engine.dispose()
        with admin_engine.connect() as conn:
            conn.execute(
                text(
                    """
                    SELECT pg_terminate_backend(pid)
                    FROM pg_stat_activity
                    WHERE datname = :db_name AND pid <> pg_backend_pid()
                    """
                ),
                {"db_name": db_name},
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
        admin_engine.dispose()


def _run_migration(conn, *, path: Path = MIGRATION_FILE, operation: str = "upgrade") -> None:
    module = _migration_module(path)
    with Operations.context(MigrationContext.configure(conn)):
        getattr(module, operation)()


def test_revision_extends_single_head() -> None:
    script = ScriptDirectory.from_config(alembic_config())
    revision = script.get_revision(REVISION)
    assert revision is not None
    assert revision.down_revision == PREVIOUS_REVISION
    assert script.get_heads() == [REVISION]


def test_migration_sql_uses_only_production_org_unit_columns() -> None:
    source = MIGRATION_FILE.read_text(encoding="utf-8")

    for unsupported_name in (
        "name_ru",
        "name_en",
        "unit_type",
        "org_level",
        "sort_order",
        "org_unit_groups",
        "deps_group",
        "setval",
    ):
        assert unsupported_name not in source

    assert "INSERT INTO public.org_units\n                (unit_id" not in source
    assert "INSERT INTO public.positions (position_id" not in source
    assert "CASCADE" not in source.upper()


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_s2_then_t3_upgrade_on_exact_production_schema() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            before_employees = conn.execute(text("SELECT COUNT(*) FROM public.employees")).scalar_one()
            before_assignments = conn.execute(
                text("SELECT COUNT(*) FROM public.person_assignments")
            ).scalar_one()
            _run_migration(conn, path=S2_MIGRATION_FILE)
            transfuse_id = conn.execute(
                text("SELECT unit_id FROM public.org_units WHERE code = 'TRANSFUSE'")
            ).scalar_one()
            _run_migration(conn)
            _run_migration(conn)

            positions = dict(
                conn.execute(
                    text(
                        """
                        SELECT name, category
                        FROM public.positions
                        WHERE name = ANY(:names)
                        ORDER BY name
                        """
                    ),
                    {"names": list(EXPECTED_POSITIONS)},
                ).all()
            )
            assert positions == EXPECTED_POSITIONS
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'инженер'")
            ).scalar_one() == 0
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'Инженер'")
            ).scalar_one() == 1

            units = {
                row.code: row
                for row in conn.execute(
                    text(
                        """
                        SELECT code, unit_id, name, parent_unit_id, group_id, is_active
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            }
            assert units["TRANSFUSE"].unit_id == transfuse_id
            assert units["TRANSFUSE"].name == "Трансфузиология"
            assert units["TRANSFUSE"].parent_unit_id == 1
            assert units["TRANSFUSE"].group_id == 2
            assert units["Amb_chem"].name == "Секция амбулаторной химиотерапии"
            assert units["Amb_chem"].parent_unit_id == 60
            assert units["Amb_chem"].group_id == 1
            assert units["COMPL"].name == "Комплаенс"
            assert units["COMPL"].parent_unit_id == 1
            assert units["COMPL"].group_id == 3

            assert conn.execute(text("SELECT COUNT(*) FROM public.employees")).scalar_one() == before_employees
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.person_assignments")
            ).scalar_one() == before_assignments


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_accepts_exact_local_units_without_duplicates() -> None:
    with _ephemeral_database(root_code="ORG_MAIN", seed_exact_units=True) as test_engine:
        with test_engine.begin() as conn:
            before = dict(
                conn.execute(
                    text(
                        """
                        SELECT code, unit_id
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            )
            _run_migration(conn)
            _run_migration(conn)
            after = dict(
                conn.execute(
                    text(
                        """
                        SELECT code, unit_id
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            )
            assert after == before
            assert len(after) == 3


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_rejects_conflicting_transfuse_atomically() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units
                        (name, code, parent_unit_id, group_id, is_active)
                    VALUES ('Конфликтующая трансфузиология', 'TRANSFUSE', 60, 3, TRUE)
                    """
                )
            )

        with test_engine.connect() as conn:
            transaction = conn.begin()
            with pytest.raises(RuntimeError, match="Conflicting organizational unit code/name"):
                _run_migration(conn)
            transaction.rollback()

        with test_engine.connect() as conn:
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'инженер'")
            ).scalar_one() == 1
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'Заведующий отделением'")
            ).scalar_one() == 0


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_refuses_to_remove_referenced_engineer_duplicate() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO public.employees (employee_id, position_id, org_unit_id)
                    VALUES (2, 502, 1)
                    """
                )
            )

        with test_engine.connect() as conn:
            transaction = conn.begin()
            with pytest.raises(RuntimeError, match="is referenced by public.employees.position_id"):
                _run_migration(conn)
            transaction.rollback()

        with test_engine.connect() as conn:
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.employees WHERE position_id = 502")
            ).scalar_one() == 1
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE position_id = 502")
            ).scalar_one() == 1


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_downgrade_removes_only_exact_owned_org_units() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            _run_migration(conn, path=S2_MIGRATION_FILE)
            _run_migration(conn)
            conn.execute(
                text(
                    """
                    UPDATE public.org_units
                    SET group_id = 2
                    WHERE code = 'COMPL'
                    """
                )
            )
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units
                        (name, code, parent_unit_id, group_id, is_active)
                    VALUES ('Unrelated unit', 'UNRELATED', 1, 3, TRUE)
                    """
                )
            )

            _run_migration(conn, operation="downgrade")

            remaining_codes = set(
                conn.execute(
                    text(
                        """
                        SELECT code
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL', 'UNRELATED')
                        """
                    )
                ).scalars()
            )
            assert remaining_codes == {"TRANSFUSE", "COMPL", "UNRELATED"}
