"""Contract tests for the Oserova HR enrollment migration."""
from __future__ import annotations

from contextlib import contextmanager
import importlib.util
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, text

from app.db.engine import engine


MIGRATION_PATH = (
    Path(__file__).resolve().parents[1]
    / "alembic"
    / "versions"
    / "p1q2r3s4t5u6_oserova_hr_reg_enrollment_grant.py"
)


def _load_migration_module():
    spec = importlib.util.spec_from_file_location("oserova_hr_reg_grant_migration", MIGRATION_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


@contextmanager
def _ephemeral_database(*, existing_hr_role: bool):
    db_name = f"corpsite_p1_role_{uuid4().hex[:12]}"
    admin_url = str(engine.url.render_as_string(hide_password=False)).rsplit("/", 1)[0] + "/postgres"
    test_url = admin_url.rsplit("/", 1)[0] + f"/{db_name}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    test_engine = create_engine(test_url)

    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))

    try:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE public.roles (
                        role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        code TEXT NOT NULL UNIQUE
                    );
                    CREATE TABLE public.users (
                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login TEXT NOT NULL UNIQUE,
                        role_id BIGINT NULL REFERENCES public.roles(role_id),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE
                    );
                    CREATE TABLE public.access_roles (
                        access_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        code TEXT NOT NULL UNIQUE,
                        is_active BOOLEAN NOT NULL DEFAULT TRUE
                    );
                    CREATE TABLE public.access_grants (
                        access_grant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        access_role_id BIGINT NOT NULL REFERENCES public.access_roles(access_role_id),
                        target_type TEXT NOT NULL,
                        target_id BIGINT NOT NULL,
                        resource_key TEXT NOT NULL,
                        scope_type TEXT NOT NULL,
                        scope_id BIGINT NULL,
                        include_subtree BOOLEAN NOT NULL,
                        starts_at TIMESTAMPTZ NOT NULL,
                        ends_at TIMESTAMPTZ NULL,
                        active_flag BOOLEAN NOT NULL,
                        granted_by_user_id BIGINT NOT NULL REFERENCES public.users(user_id),
                        reason TEXT NULL
                    );

                    INSERT INTO public.roles (name, code)
                    VALUES ('Administrator', 'ADMIN');
                    INSERT INTO public.users (login, role_id, is_active)
                    SELECT 'admin', role_id, TRUE FROM public.roles WHERE code = 'ADMIN';
                    INSERT INTO public.users (login, role_id, is_active)
                    VALUES ('oserova.aa', NULL, TRUE);
                    INSERT INTO public.access_roles (code, is_active)
                    VALUES ('HR_ENROLLMENT_MANAGER', TRUE);
                    """
                )
            )
            if existing_hr_role:
                conn.execute(
                    text(
                        """
                        INSERT INTO public.roles (name, code)
                        VALUES ('outdated name', 'HR_reg')
                        """
                    )
                )
        yield test_engine
    finally:
        test_engine.dispose()
        with admin_engine.connect() as conn:
            conn.execute(
                text(
                    """
                    SELECT pg_terminate_backend(pid)
                    FROM pg_stat_activity
                    WHERE datname = :db_name AND pid <> pg_backend_pid()
                    """
                ),
                {"db_name": db_name},
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
        admin_engine.dispose()


def _run_upgrade(conn) -> None:
    migration = _load_migration_module()
    with Operations.context(MigrationContext.configure(conn)):
        migration.upgrade()


def test_upgrade_is_code_and_login_based_and_keeps_grant_personal(monkeypatch) -> None:
    migration = _load_migration_module()
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.upgrade()

    assert migration.down_revision == "o1p2q3r4s5t6"
    assert len(statements) == 3
    sql = "\n".join(statements)
    assert "VALUES ('HR_reg', 'сотрудник1 ОК')" in sql
    assert "ON CONFLICT (code)" in sql
    assert "is_active" not in statements[0]
    assert "lower(u.login) = 'oserova.aa'" in sql
    assert "r.code = 'HR_reg'" in sql
    assert "ar.code = 'HR_ENROLLMENT_MANAGER'" in sql
    assert "'USER'" in sql
    assert "'GLOBAL'" in sql
    assert "target_type = 'ROLE'" not in statements[2]
    assert "existing.active_flag = TRUE" in statements[2]
    assert "existing.target_id = target.user_id" in statements[2]
    assert "ends_at" in statements[2]
    assert "NULL" in statements[2]


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
@pytest.mark.parametrize("existing_hr_role", [False, True])
def test_upgrade_supports_roles_without_is_active_and_is_idempotent(existing_hr_role: bool) -> None:
    with _ephemeral_database(existing_hr_role=existing_hr_role) as test_engine:
        with test_engine.begin() as conn:
            role_columns = set(
                conn.execute(
                    text(
                        """
                        SELECT column_name
                        FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'roles'
                        """
                    )
                ).scalars()
            )
            assert role_columns == {"role_id", "name", "code"}

            _run_upgrade(conn)
            _run_upgrade(conn)

            role = conn.execute(
                text("SELECT role_id, name FROM public.roles WHERE code = 'HR_reg'")
            ).one()
            assert role.name == "сотрудник1 ОК"
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.roles WHERE code = 'HR_reg'")
            ).scalar_one() == 1
            assert conn.execute(
                text("SELECT role_id FROM public.users WHERE login = 'oserova.aa'")
            ).scalar_one() == role.role_id
            assert conn.execute(
                text(
                    """
                    SELECT COUNT(*)
                    FROM public.access_grants grant_row
                    JOIN public.access_roles access_role
                      ON access_role.access_role_id = grant_row.access_role_id
                    JOIN public.users target ON target.user_id = grant_row.target_id
                    WHERE access_role.code = 'HR_ENROLLMENT_MANAGER'
                      AND target.login = 'oserova.aa'
                      AND grant_row.target_type = 'USER'
                      AND grant_row.active_flag = TRUE
                    """
                )
            ).scalar_one() == 1


def test_downgrade_only_removes_the_migration_owned_grant(monkeypatch) -> None:
    migration = _load_migration_module()
    statements: list[str] = []
    monkeypatch.setattr(migration.op, "execute", statements.append)

    migration.downgrade()

    assert len(statements) == 1
    assert "Seed: Oserova personal HR_ENROLLMENT_MANAGER grant" in statements[0]
    assert "lower(target.login) = 'oserova.aa'" in statements[0]
