from __future__ import annotations

from contextlib import contextmanager
import importlib.util
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from sqlalchemy import create_engine, text

from app.db.engine import engine


ROOT = Path(__file__).resolve().parents[1]
MIGRATION_PATH = (
    ROOT
    / "alembic"
    / "versions"
    / "w6x7y8z9a0b1_wp_cl_002_control_list_export_permission.py"
)


def _load_migration():
    spec = importlib.util.spec_from_file_location("wp_cl_002_permission", MIGRATION_PATH)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


@contextmanager
def _ephemeral_database():
    database_name = f"corpsite_wpcl002_{uuid4().hex[:12]}_test"
    admin_url = (
        str(engine.url.render_as_string(hide_password=False)).rsplit("/", 1)[0]
        + "/postgres"
    )
    database_url = admin_url.rsplit("/", 1)[0] + f"/{database_name}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    test_engine = create_engine(database_url)

    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{database_name}"'))

    try:
        with test_engine.begin() as conn:
            conn.execute(text("""
                CREATE TABLE public.roles (
                    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code TEXT NOT NULL UNIQUE,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE
                );
                    CREATE TABLE public.users (
                        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        login TEXT NOT NULL UNIQUE,
                        role_id BIGINT NULL REFERENCES public.roles(role_id),
                        employee_id BIGINT NULL,
                        is_active BOOLEAN NOT NULL DEFAULT TRUE
                    );
                    CREATE TABLE public.employees (
                        employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        person_id BIGINT NULL,
                        operational_status TEXT NOT NULL DEFAULT 'active'
                    );
                    CREATE TABLE public.person_assignments (
                        assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        person_id BIGINT NOT NULL,
                        position_id BIGINT NULL,
                        org_unit_id BIGINT NULL,
                        active_flag BOOLEAN NOT NULL DEFAULT TRUE,
                        lifecycle_status TEXT NOT NULL DEFAULT 'active'
                    );
                CREATE TABLE public.access_roles (
                    access_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    code TEXT NOT NULL UNIQUE,
                    name TEXT NOT NULL,
                    description TEXT NULL,
                    access_level TEXT NOT NULL,
                    level_rank INTEGER NOT NULL,
                    is_system BOOLEAN NOT NULL DEFAULT FALSE,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                );
                CREATE TABLE public.access_grants (
                    grant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    access_role_id BIGINT NOT NULL REFERENCES public.access_roles(access_role_id),
                    target_type TEXT NOT NULL,
                    target_id BIGINT NOT NULL,
                    resource_key TEXT NOT NULL DEFAULT '*',
                    scope_type TEXT NOT NULL DEFAULT 'GLOBAL',
                    scope_id BIGINT NULL,
                    include_subtree BOOLEAN NOT NULL DEFAULT FALSE,
                    starts_at TIMESTAMPTZ NOT NULL DEFAULT statement_timestamp(),
                    ends_at TIMESTAMPTZ NULL,
                    active_flag BOOLEAN NOT NULL DEFAULT TRUE,
                    granted_by_user_id BIGINT NOT NULL REFERENCES public.users(user_id),
                    reason TEXT NULL
                );
                INSERT INTO public.roles (code) VALUES
                    ('HR_HEAD'), ('HR_reg'), ('HR_ENROLLMENT_ONLY'), ('ADMIN');
                INSERT INTO public.users (login, role_id)
                SELECT lower(code), role_id FROM public.roles;
                INSERT INTO public.access_roles
                    (code, name, access_level, level_rank, is_system)
                VALUES
                    ('HR_ENROLLMENT_MANAGER', 'Enrollment', 'MANAGER', 20, TRUE);
            """))
        yield test_engine
    finally:
        test_engine.dispose()
        with admin_engine.connect() as conn:
            conn.execute(text("""
                SELECT pg_terminate_backend(pid)
                FROM pg_stat_activity
                WHERE datname = :database_name AND pid <> pg_backend_pid()
            """), {"database_name": database_name})
            conn.execute(text(f'DROP DATABASE IF EXISTS "{database_name}"'))
        admin_engine.dispose()


def _run(conn, operation: str) -> None:
    migration = _load_migration()
    with Operations.context(MigrationContext.configure(conn)):
        getattr(migration, operation)()


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_real_postgresql_upgrade_and_downgrade() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            _run(conn, "upgrade")
            grants = conn.execute(text("""
                SELECT r.code
                FROM public.access_grants g
                JOIN public.access_roles ar USING (access_role_id)
                JOIN public.roles r ON g.target_type = 'ROLE' AND g.target_id = r.role_id
                WHERE ar.code = 'CONTROL_LIST_EXPORT'
            """)).scalars().all()
            assert grants == ["HR_HEAD"]

            _run(conn, "downgrade")
            assert conn.execute(text(
                "SELECT count(*) FROM public.access_roles WHERE code='CONTROL_LIST_EXPORT'"
            )).scalar_one() == 0


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_real_postgresql_upgrade_rejects_preexisting_permission_atomically() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO public.access_roles (code, name, access_level, level_rank, is_system)
                VALUES ('CONTROL_LIST_EXPORT', 'Preexisting', 'READ', 10, FALSE)
            """))

        with pytest.raises(Exception, match="code already exists"):
            with test_engine.begin() as conn:
                _run(conn, "upgrade")

        with test_engine.connect() as conn:
            row = conn.execute(
                text(
                    "SELECT name, access_level FROM public.access_roles "
                    "WHERE code='CONTROL_LIST_EXPORT'"
                )
            ).one()
            assert tuple(row) == ("Preexisting", "READ")
            assert conn.execute(text("""
                SELECT count(*) FROM public.access_grants g
                JOIN public.access_roles ar USING (access_role_id)
                WHERE ar.code='CONTROL_LIST_EXPORT'
            """)).scalar_one() == 0


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_real_postgresql_downgrade_preserves_later_personal_grant() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            _run(conn, "upgrade")
            conn.execute(text("""
                INSERT INTO public.access_grants
                    (access_role_id, target_type, target_id, granted_by_user_id, reason)
                SELECT ar.access_role_id, 'USER', u.user_id, u.user_id, 'later personal grant'
                FROM public.access_roles ar CROSS JOIN public.users u
                WHERE ar.code='CONTROL_LIST_EXPORT' AND u.login='admin'
            """))
            _run(conn, "downgrade")

            assert conn.execute(text(
                "SELECT count(*) FROM public.access_roles WHERE code='CONTROL_LIST_EXPORT'"
            )).scalar_one() == 1
            grants = conn.execute(text("""
                SELECT target_type, reason FROM public.access_grants g
                JOIN public.access_roles ar USING (access_role_id)
                WHERE ar.code='CONTROL_LIST_EXPORT' ORDER BY g.grant_id
            """)).all()
            assert [tuple(row) for row in grants] == [("USER", "later personal grant")]


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_real_postgresql_upgrade_failure_leaves_no_partial_permission_or_grant() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(text("UPDATE public.roles SET is_active=FALSE WHERE code='HR_HEAD'"))

        with pytest.raises(Exception, match="exactly one active role"):
            with test_engine.begin() as conn:
                _run(conn, "upgrade")

        with test_engine.connect() as conn:
            assert conn.execute(text(
                "SELECT count(*) FROM public.access_roles WHERE code='CONTROL_LIST_EXPORT'"
            )).scalar_one() == 0
            assert conn.execute(text("SELECT count(*) FROM public.access_grants")).scalar_one() == 0


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_real_postgresql_rbac_matrix_has_no_role_or_admin_bypass(monkeypatch) -> None:
    import app.services.access_resolver_service as resolver
    from app.security.admin_permissions import (
        CONTROL_LIST_EXPORT_PERMISSION,
        has_admin_permission,
    )

    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            _run(conn, "upgrade")
            conn.execute(text("""
                INSERT INTO public.access_grants
                    (access_role_id, target_type, target_id, granted_by_user_id, reason)
                SELECT ar.access_role_id, 'ROLE', r.role_id, admin.user_id, 'enrollment only'
                FROM public.access_roles ar
                JOIN public.roles r ON r.code='HR_ENROLLMENT_ONLY'
                JOIN public.users admin ON admin.login='admin'
                WHERE ar.code='HR_ENROLLMENT_MANAGER'
            """))

        monkeypatch.setattr(resolver, "engine", test_engine)

        def allowed(login: str) -> bool:
            with test_engine.connect() as conn:
                user_id = conn.execute(
                    text("SELECT user_id FROM public.users WHERE login=:login"),
                    {"login": login},
                ).scalar_one()
            return has_admin_permission(user_id, CONTROL_LIST_EXPORT_PERMISSION)

        assert allowed("hr_head") is True
        assert allowed("hr_reg") is False
        assert allowed("hr_enrollment_only") is False
        assert allowed("admin") is False

        with test_engine.begin() as conn:
            conn.execute(text("""
                INSERT INTO public.access_grants
                    (access_role_id, target_type, target_id, granted_by_user_id, reason)
                SELECT ar.access_role_id, 'USER', target.user_id, admin.user_id, 'personal export'
                FROM public.access_roles ar
                JOIN public.users target ON target.login='hr_reg'
                JOIN public.users admin ON admin.login='admin'
                WHERE ar.code='CONTROL_LIST_EXPORT'
            """))
            conn.execute(text("""
                INSERT INTO public.access_grants
                    (access_role_id, target_type, target_id, granted_by_user_id, reason)
                SELECT ar.access_role_id, 'USER', target.user_id, target.user_id,
                       'admin explicit export'
                FROM public.access_roles ar
                JOIN public.users target ON target.login='admin'
                WHERE ar.code='CONTROL_LIST_EXPORT'
            """))

        assert allowed("hr_reg") is True
        assert allowed("admin") is True
