# tests/test_db_sequence_isolation.py
"""Regression tests for PostgreSQL sequence sync in pytest infrastructure."""
from __future__ import annotations

from uuid import uuid4

import pytest
from sqlalchemy import text

from app.db.engine import engine
from tests.conftest import create_role, get_columns, insert_returning_id, table_exists
from tests.db_sequence_helpers import (
    assert_sequence_not_behind,
    get_owned_sequence,
    sync_common_seed_sequences,
    sync_owned_sequence,
)


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_get_owned_sequence_for_roles_identity_column() -> None:
    with engine.connect() as conn:
        seq = get_owned_sequence(conn, "roles", "role_id")
        assert seq is not None
        assert seq.endswith("roles_role_id_seq")


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_roles_sequence_recovers_after_explicit_pk_insert() -> None:
    suffix = uuid4().hex[:8]
    explicit_code = f"pytest_seq_explicit_{suffix}"
    generated_code = f"pytest_seq_generated_{suffix}"
    explicit_role_id: int | None = None

    try:
        with engine.begin() as conn:
            assert table_exists(conn, "roles")
            max_before = conn.execute(text("SELECT COALESCE(MAX(role_id), 0) FROM public.roles")).scalar_one()
            explicit_role_id = int(max_before) + 1000

            cols = get_columns(conn, "roles")
            values = {"role_id": explicit_role_id, "name": explicit_code}
            if "code" in cols:
                values["code"] = explicit_code
            col_list = ", ".join(values.keys())
            bind_list = ", ".join(f":{k}" for k in values.keys())
            conn.execute(
                text(
                    f"""
                    INSERT INTO public.roles ({col_list})
                    OVERRIDING SYSTEM VALUE
                    VALUES ({bind_list})
                    """
                ),
                values,
            )
            sync_owned_sequence(conn, "roles", "role_id")

            generated_role_id = create_role(conn, generated_code)
            assert generated_role_id != explicit_role_id
            assert generated_role_id > explicit_role_id
            assert_sequence_not_behind(conn, "roles", "role_id")
    finally:
        with engine.begin() as conn:
            conn.execute(
                text(
                    """
                    DELETE FROM public.roles
                    WHERE code = ANY(:codes)
                    """
                ),
                {"codes": [explicit_code, generated_code]},
            )
            sync_owned_sequence(conn, "roles", "role_id")


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_seed_like_role_creation_is_repeatable() -> None:
    created_codes: list[str] = []
    try:
        for _ in range(3):
            suffix = uuid4().hex[:8]
            code = f"pytest_seq_repeat_{suffix}"
            created_codes.append(code)
            with engine.begin() as conn:
                role_id = create_role(conn, code)
                assert role_id > 0
                assert_sequence_not_behind(conn, "roles", "role_id")
    finally:
        with engine.begin() as conn:
            conn.execute(
                text("DELETE FROM public.roles WHERE code = ANY(:codes)"),
                {"codes": created_codes},
            )
            sync_common_seed_sequences(conn)


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_sync_common_seed_sequences_covers_core_tables() -> None:
    with engine.begin() as conn:
        synced = sync_common_seed_sequences(conn)
        assert synced
        for table_name, pk_column in (
            ("roles", "role_id"),
            ("users", "user_id"),
        ):
            if table_exists(conn, table_name):
                assert_sequence_not_behind(conn, table_name, pk_column)


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_insert_returning_id_syncs_empty_table_sequence() -> None:
    suffix = uuid4().hex[:8]
    table = f"pytest_seq_tmp_{suffix}"
    try:
        with engine.begin() as conn:
            conn.execute(
                text(
                    f"""
                    CREATE TABLE public.{table} (
                        item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        label TEXT NOT NULL
                    )
                    """
                )
            )
            sync_owned_sequence(conn, table, "item_id")
            item_id = insert_returning_id(
                conn,
                table=table,
                id_col="item_id",
                values={"label": "first"},
            )
            assert item_id >= 1
            assert_sequence_not_behind(conn, table, "item_id")
    finally:
        with engine.begin() as conn:
            conn.execute(text(f"DROP TABLE IF EXISTS public.{table}"))
