"""Focused tests for t3u4v5w6x7y reference-data migration."""
from __future__ import annotations

from contextlib import contextmanager
from importlib.util import module_from_spec, spec_from_file_location
from pathlib import Path
from uuid import uuid4

import pytest
from alembic.operations import Operations
from alembic.runtime.migration import MigrationContext
from alembic.script import ScriptDirectory
from sqlalchemy import create_engine, text

from app.db.engine import engine
from tests.alembic_test_helpers import alembic_config


REVISION = "t3u4v5w6x7y"
PREVIOUS_REVISION = "s2t3u4v5w6x"
MIGRATION_FILE = (
    Path(__file__).resolve().parents[1]
    / "alembic"
    / "versions"
    / "t3u4v5w6x7y_reference_positions_org_units.py"
)

EXPECTED_POSITIONS = {
    "Инженер": "technical",
    "Заведующий отделением": "other",
    "Машинист по стирке белья": "technical",
    "Социальный работник": "medical",
    "Медицинский статистик": "medical",
    "Техник": "technical",
    "Заведующий ОТ и ТБ": "leaders",
    "Санитар по транспортировке пациентов": "medical",
    "Врач-эксперт": "medical",
    "Руководитель административно-хозяйственной службы": "leaders",
    "Буфетчица": "technical",
    "Бухгалтер-экономист": "admin",
    "Руководитель отдела": "leaders",
    "Старший ординатор": "medical",
    "Комплаенс-офицер": "admin",
    "Главный инженер": "technical",
}


def _db_available() -> bool:
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return True
    except Exception:
        return False


def _migration_module():
    spec = spec_from_file_location("reference_positions_org_units_migration", MIGRATION_FILE)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load migration from {MIGRATION_FILE}")
    module = module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@contextmanager
def _ephemeral_database(*, root_code: str = "mmc_root", seed_exact_units: bool = False):
    db_name = f"corpsite_ref_seed_{uuid4().hex[:12]}"
    admin_url = str(engine.url.render_as_string(hide_password=False)).rsplit("/", 1)[0] + "/postgres"
    test_url = admin_url.rsplit("/", 1)[0] + f"/{db_name}"
    admin_engine = create_engine(admin_url, isolation_level="AUTOCOMMIT")
    test_engine = create_engine(test_url)

    with admin_engine.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{db_name}"'))

    try:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    CREATE TABLE public.positions (
                        position_id BIGINT PRIMARY KEY,
                        name TEXT NOT NULL,
                        category VARCHAR NULL
                    );
                    CREATE TABLE public.org_unit_groups (
                        group_id INTEGER PRIMARY KEY,
                        group_name TEXT NOT NULL
                    );
                    CREATE TABLE public.org_units (
                        unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name TEXT NOT NULL,
                        code TEXT NOT NULL UNIQUE,
                        parent_unit_id BIGINT NULL REFERENCES public.org_units(unit_id),
                        is_active BOOLEAN NOT NULL DEFAULT TRUE,
                        name_ru TEXT NULL,
                        name_en TEXT NULL,
                        unit_type TEXT NULL,
                        org_level INTEGER NULL,
                        sort_order1 INTEGER NULL,
                        sort_order2 INTEGER NULL,
                        group_id INTEGER NULL
                    );
                    CREATE TABLE public.employees (
                        employee_id BIGINT PRIMARY KEY,
                        position_id BIGINT NOT NULL REFERENCES public.positions(position_id),
                        org_unit_id BIGINT NOT NULL REFERENCES public.org_units(unit_id)
                    );
                    CREATE TABLE public.person_assignments (
                        assignment_id BIGINT PRIMARY KEY,
                        position_id BIGINT NOT NULL REFERENCES public.positions(position_id),
                        org_unit_id BIGINT NOT NULL REFERENCES public.org_units(unit_id)
                    );
                    """
                )
            )
            conn.execute(
                text(
                    """
                    INSERT INTO public.positions (position_id, name, category)
                    VALUES
                        (501, 'Инженер', 'technical'),
                        (502, 'инженер', 'technical'),
                        (900, 'Базовая должность', 'other');
                    """
                )
            )
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units
                        (unit_id, name, name_ru, code, parent_unit_id, group_id, is_active)
                    VALUES
                        (1001, 'Организация', NULL, :root_code, NULL, NULL, TRUE),
                        (2002, 'Диспансер', NULL, 'DISP', 1001, 1, TRUE)
                    """
                ),
                {"root_code": root_code},
            )
            if seed_exact_units:
                conn.execute(
                    text(
                        """
                        INSERT INTO public.org_units
                            (unit_id, name, name_ru, name_en, code, parent_unit_id,
                             group_id, is_active, unit_type, org_level, sort_order1, sort_order2)
                        VALUES
                            (3003, 'Трансфузиология', 'Трансфузиология', NULL,
                             'TRANSFUSE', 1001, 2, TRUE, NULL, NULL, NULL, NULL),
                            (3004, 'Секция амбулаторной химиотерапии',
                             'Секция амбулаторной химиотерапии', 'Amb chemotherapy section',
                             'Amb_chem', 2002, 1, TRUE, 'BRANCH', 2, 59, NULL),
                            (3005, 'Комплаенс', 'Комплаенс', NULL,
                             'COMPL', 1001, 3, TRUE, NULL, NULL, 58, NULL)
                        """
                    )
                )
            conn.execute(
                text(
                    """
                    INSERT INTO public.employees (employee_id, position_id, org_unit_id)
                    VALUES (1, 900, 1001);
                    INSERT INTO public.person_assignments (assignment_id, position_id, org_unit_id)
                    VALUES (1, 900, 1001)
                    """
                )
            )
        yield test_engine
    finally:
        test_engine.dispose()
        with admin_engine.connect() as conn:
            conn.execute(
                text(
                    """
                    SELECT pg_terminate_backend(pid)
                    FROM pg_stat_activity
                    WHERE datname = :db_name AND pid <> pg_backend_pid()
                    """
                ),
                {"db_name": db_name},
            )
            conn.execute(text(f'DROP DATABASE IF EXISTS "{db_name}"'))
        admin_engine.dispose()


def _run_upgrade(conn) -> None:
    module = _migration_module()
    with Operations.context(MigrationContext.configure(conn)):
        module.upgrade()


def test_revision_extends_single_head() -> None:
    script = ScriptDirectory.from_config(alembic_config())
    revision = script.get_revision(REVISION)
    assert revision is not None
    assert revision.down_revision == PREVIOUS_REVISION
    assert script.get_heads() == [REVISION]


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_creates_units_for_production_shape_without_group_rows() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            before_employees = conn.execute(text("SELECT COUNT(*) FROM public.employees")).scalar_one()
            before_assignments = conn.execute(
                text("SELECT COUNT(*) FROM public.person_assignments")
            ).scalar_one()
            assert conn.execute(text("SELECT COUNT(*) FROM public.org_unit_groups")).scalar_one() == 0
            _run_upgrade(conn)
            _run_upgrade(conn)

            positions = dict(
                conn.execute(
                    text(
                        """
                        SELECT name, category
                        FROM public.positions
                        WHERE name = ANY(:names)
                        ORDER BY name
                        """
                    ),
                    {"names": list(EXPECTED_POSITIONS)},
                ).all()
            )
            assert positions == EXPECTED_POSITIONS
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'инженер'")
            ).scalar_one() == 0
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'Инженер'")
            ).scalar_one() == 1

            units = {
                row.code: row
                for row in conn.execute(
                    text(
                        """
                        SELECT code, unit_id, name, name_ru, name_en, parent_unit_id,
                               group_id, is_active, unit_type, org_level, sort_order1
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            }
            assert units["TRANSFUSE"].name == "Трансфузиология"
            assert units["TRANSFUSE"].parent_unit_id == 1001
            assert units["TRANSFUSE"].group_id == 2
            assert units["Amb_chem"].name == "Секция амбулаторной химиотерапии"
            assert units["Amb_chem"].parent_unit_id == 2002
            assert units["Amb_chem"].group_id == 1
            assert units["Amb_chem"].unit_type == "BRANCH"
            assert units["Amb_chem"].org_level == 2
            assert units["COMPL"].name == "Комплаенс"
            assert units["COMPL"].parent_unit_id == 1001
            assert units["COMPL"].group_id == 3

            assert conn.execute(text("SELECT COUNT(*) FROM public.employees")).scalar_one() == before_employees
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.person_assignments")
            ).scalar_one() == before_assignments


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_accepts_exact_local_units_without_duplicates() -> None:
    with _ephemeral_database(root_code="ORG_MAIN", seed_exact_units=True) as test_engine:
        with test_engine.begin() as conn:
            before = dict(
                conn.execute(
                    text(
                        """
                        SELECT code, unit_id
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            )
            _run_upgrade(conn)
            _run_upgrade(conn)
            after = dict(
                conn.execute(
                    text(
                        """
                        SELECT code, unit_id
                        FROM public.org_units
                        WHERE code IN ('TRANSFUSE', 'Amb_chem', 'COMPL')
                        """
                    )
                ).all()
            )
            assert after == before
            assert len(after) == 3


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_rejects_conflicting_transfuse_atomically() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO public.org_units
                        (name, name_ru, code, parent_unit_id, group_id, is_active)
                    VALUES ('Конфликтующая трансфузиология', 'Конфликтующая трансфузиология',
                            'TRANSFUSE', 2002, 3, TRUE)
                    """
                )
            )

        with test_engine.connect() as conn:
            transaction = conn.begin()
            with pytest.raises(RuntimeError, match="Conflicting organizational unit code/name"):
                _run_upgrade(conn)
            transaction.rollback()

        with test_engine.connect() as conn:
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'инженер'")
            ).scalar_one() == 1
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE name = 'Заведующий отделением'")
            ).scalar_one() == 0


@pytest.mark.skipif(not _db_available(), reason="PostgreSQL not available")
def test_upgrade_refuses_to_remove_referenced_engineer_duplicate() -> None:
    with _ephemeral_database() as test_engine:
        with test_engine.begin() as conn:
            conn.execute(
                text(
                    """
                    INSERT INTO public.employees (employee_id, position_id, org_unit_id)
                    VALUES (2, 502, 1001)
                    """
                )
            )

        with test_engine.connect() as conn:
            transaction = conn.begin()
            with pytest.raises(RuntimeError, match="is referenced by public.employees.position_id"):
                _run_upgrade(conn)
            transaction.rollback()

        with test_engine.connect() as conn:
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.employees WHERE position_id = 502")
            ).scalar_one() == 1
            assert conn.execute(
                text("SELECT COUNT(*) FROM public.positions WHERE position_id = 502")
            ).scalar_one() == 1
