"""Re-export verification domain constants."""
from __future__ import annotations

from app.db.models.personnel_verification import (
    ALLOWED_CONTROL_POINTS,
    ATTESTATION_DECISION_REJECTED,
    ATTESTATION_DECISION_VERIFIED,
    ATTESTATION_DECISIONS,
    CONTROL_POINT_EMPLOYMENT_EPISODE,
    CONTROL_POINT_MEDICAL_CATEGORY,
    OBJECT_TYPE_PERSON_EXTERNAL_EMPLOYMENT,
    OPEN_TASK_STATUSES,
    POLICY_STATUS_ACTIVE,
    POLICY_STATUS_DRAFT,
    POLICY_STATUS_INACTIVE,
    POLICY_STATUSES,
    TASK_STATUS_CANCELLED,
    TASK_STATUS_COMPLETED,
    TASK_STATUS_PENDING,
    TASK_STATUS_REJECTED,
    TASK_STATUSES,
    TERMINAL_TASK_STATUSES,
)

# Derived verification state codes (not a second SSoT column).
VERIFICATION_STATE_NOT_REQUIRED = "not_required"
VERIFICATION_STATE_PENDING = "pending"
VERIFICATION_STATE_VERIFIED = "verified"
VERIFICATION_STATE_REJECTED = "rejected"

__all__ = [
    "ALLOWED_CONTROL_POINTS",
    "ATTESTATION_DECISION_REJECTED",
    "ATTESTATION_DECISION_VERIFIED",
    "ATTESTATION_DECISIONS",
    "CONTROL_POINT_EMPLOYMENT_EPISODE",
    "CONTROL_POINT_MEDICAL_CATEGORY",
    "OBJECT_TYPE_PERSON_EXTERNAL_EMPLOYMENT",
    "OPEN_TASK_STATUSES",
    "POLICY_STATUS_ACTIVE",
    "POLICY_STATUS_DRAFT",
    "POLICY_STATUS_INACTIVE",
    "POLICY_STATUSES",
    "TASK_STATUS_CANCELLED",
    "TASK_STATUS_COMPLETED",
    "TASK_STATUS_PENDING",
    "TASK_STATUS_REJECTED",
    "TASK_STATUSES",
    "TERMINAL_TASK_STATUSES",
    "VERIFICATION_STATE_NOT_REQUIRED",
    "VERIFICATION_STATE_PENDING",
    "VERIFICATION_STATE_REJECTED",
    "VERIFICATION_STATE_VERIFIED",
]
