"""baseline

Revision ID: 02b0d99063cd
Revises:
Create Date: 2026-02-22 14:33:16.675671

"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "02b0d99063cd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        r"""
        -- Baseline schema (PostgreSQL)

        -- Roles
        CREATE TABLE public.roles (
            role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            code TEXT NOT NULL UNIQUE
        );

        -- Org units
        CREATE TABLE public.org_units (
            unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            code TEXT NOT NULL UNIQUE,
            parent_unit_id BIGINT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            CONSTRAINT fk_org_units_parent
                FOREIGN KEY (parent_unit_id)
                REFERENCES public.org_units(unit_id)
                ON DELETE SET NULL
        );

        -- Users
        CREATE TABLE public.users (
            user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT NOT NULL,
            google_login TEXT NULL,
            phone TEXT NULL,
            telegram_id BIGINT NULL,
            role_id BIGINT NOT NULL,
            unit_id BIGINT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            telegram_username TEXT NULL,
            telegram_bound_at TIMESTAMPTZ NULL,
            login TEXT NULL,
            password_hash TEXT NULL,
            CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES public.roles(role_id),
            CONSTRAINT fk_users_unit FOREIGN KEY (unit_id) REFERENCES public.org_units(unit_id)
        );

        -- User supervisors (hierarchy)
        CREATE TABLE public.user_supervisors (
            user_id BIGINT NOT NULL,
            supervisor_id BIGINT NOT NULL,
            PRIMARY KEY (user_id),
            CONSTRAINT fk_user_supervisors_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_user_supervisors_supervisor
                FOREIGN KEY (supervisor_id)
                REFERENCES public.users(user_id)
                ON DELETE RESTRICT
        );

        -- Reporting periods
        CREATE TABLE public.reporting_periods (
            period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kind TEXT NOT NULL,
            date_start DATE NOT NULL,
            date_end DATE NOT NULL,
            label TEXT NULL,
            is_closed BOOLEAN NOT NULL DEFAULT FALSE
        );

        -- Task statuses
        CREATE TABLE public.task_statuses (
            status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name_ru TEXT NOT NULL,
            is_terminal BOOLEAN NOT NULL DEFAULT FALSE
        );

        -- Regular tasks (templates)
        CREATE TABLE public.regular_tasks (
            regular_task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            periodicity TEXT NULL,
            initiator_role_id BIGINT NULL,
            target_role_id BIGINT NULL,
            assignment_scope TEXT NULL,
            template_link TEXT NULL,
            order_link TEXT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            description TEXT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            code TEXT NULL,
            executor_role_id BIGINT NULL,
            schedule_type TEXT NULL,
            schedule_params JSONB NOT NULL DEFAULT '{}'::jsonb,
            create_offset_days INTEGER NOT NULL DEFAULT 0,
            due_offset_days INTEGER NOT NULL DEFAULT 0,
            created_by_user_id BIGINT NULL,
            updated_at TIMESTAMPTZ NULL,
            owner_unit_id BIGINT NULL,
            deadline_offset_days INTEGER NOT NULL DEFAULT 0,
            escalation_offset_days INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT fk_regular_tasks_initiator_role FOREIGN KEY (initiator_role_id) REFERENCES public.roles(role_id),
            CONSTRAINT fk_regular_tasks_target_role FOREIGN KEY (target_role_id) REFERENCES public.roles(role_id),
            CONSTRAINT fk_regular_tasks_executor_role FOREIGN KEY (executor_role_id) REFERENCES public.roles(role_id),
            CONSTRAINT fk_regular_tasks_created_by FOREIGN KEY (created_by_user_id) REFERENCES public.users(user_id),
            CONSTRAINT fk_regular_tasks_owner_unit FOREIGN KEY (owner_unit_id) REFERENCES public.org_units(unit_id)
        );

        -- Tasks (instances)
        CREATE TABLE public.tasks (
            task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            period_id BIGINT NOT NULL,
            regular_task_id BIGINT NULL,
            title TEXT NOT NULL,
            description TEXT NULL,
            initiator_user_id BIGINT NULL,
            executor_role_id BIGINT NOT NULL,
            assignment_scope TEXT NULL,
            status_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NULL,
            due_date TIMESTAMPTZ NULL,
            CONSTRAINT fk_tasks_period FOREIGN KEY (period_id) REFERENCES public.reporting_periods(period_id),
            CONSTRAINT fk_tasks_regular_task FOREIGN KEY (regular_task_id) REFERENCES public.regular_tasks(regular_task_id),
            CONSTRAINT fk_tasks_initiator_user FOREIGN KEY (initiator_user_id) REFERENCES public.users(user_id),
            CONSTRAINT fk_tasks_executor_role FOREIGN KEY (executor_role_id) REFERENCES public.roles(role_id),
            CONSTRAINT fk_tasks_status FOREIGN KEY (status_id) REFERENCES public.task_statuses(status_id)
        );

        -- Task reports
        CREATE TABLE public.task_reports (
            report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id BIGINT NOT NULL,
            report_link TEXT NULL,
            submitted_at TIMESTAMPTZ NULL,
            submitted_by BIGINT NULL,
            approved_at TIMESTAMPTZ NULL,
            approved_by BIGINT NULL,
            current_comment TEXT NULL,
            CONSTRAINT fk_task_reports_task
                FOREIGN KEY (task_id)
                REFERENCES public.tasks(task_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_task_reports_submitted_by FOREIGN KEY (submitted_by) REFERENCES public.users(user_id),
            CONSTRAINT fk_task_reports_approved_by FOREIGN KEY (approved_by) REFERENCES public.users(user_id)
        );

        -- Notifications
        CREATE TABLE public.notifications (
            notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            channel TEXT NOT NULL,
            recipient_user_id BIGINT NOT NULL,
            related_task_id BIGINT NULL,
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            sent_at TIMESTAMPTZ NULL,
            status TEXT NOT NULL DEFAULT 'PENDING',
            CONSTRAINT fk_notifications_recipient
                FOREIGN KEY (recipient_user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_notifications_task
                FOREIGN KEY (related_task_id)
                REFERENCES public.tasks(task_id)
                ON DELETE SET NULL
        );

        -- Generic audit log
        CREATE TABLE public.audit_log (
            audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            happened_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            actor_user_id BIGINT NULL,
            entity TEXT NOT NULL,
            entity_id BIGINT NULL,
            action TEXT NOT NULL,
            before_data JSONB NULL,
            after_data JSONB NULL,
            CONSTRAINT fk_audit_log_actor
                FOREIGN KEY (actor_user_id)
                REFERENCES public.users(user_id)
                ON DELETE SET NULL
        );

        -- Telegram bindings
        CREATE TABLE public.tg_bindings (
            tg_user_id BIGINT PRIMARY KEY,
            user_id BIGINT NOT NULL UNIQUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NULL,
            CONSTRAINT fk_tg_bindings_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE
        );

        -- Task events (event store)
        CREATE TABLE public.task_events (
            audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task_id BIGINT NOT NULL,
            event_type TEXT NOT NULL,
            actor_user_id BIGINT NULL,
            actor_role_id BIGINT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            payload JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT fk_task_events_task
                FOREIGN KEY (task_id)
                REFERENCES public.tasks(task_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_task_events_actor_user
                FOREIGN KEY (actor_user_id)
                REFERENCES public.users(user_id)
                ON DELETE SET NULL,
            CONSTRAINT fk_task_events_actor_role
                FOREIGN KEY (actor_role_id)
                REFERENCES public.roles(role_id)
                ON DELETE SET NULL
        );

        -- Task event recipients (routing)
        CREATE TABLE public.task_event_recipients (
            audit_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL,
            PRIMARY KEY (audit_id, user_id),
            CONSTRAINT fk_task_event_recipients_event
                FOREIGN KEY (audit_id)
                REFERENCES public.task_events(audit_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_task_event_recipients_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE
        );

        -- Task event deliveries (delivery attempts)
        CREATE TABLE public.task_event_deliveries (
            audit_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL,
            channel TEXT NOT NULL,
            status TEXT NOT NULL,
            error_code TEXT NULL,
            error_text TEXT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            sent_at TIMESTAMPTZ NULL,
            PRIMARY KEY (audit_id, user_id, channel),
            CONSTRAINT fk_task_event_deliveries_event
                FOREIGN KEY (audit_id)
                REFERENCES public.task_events(audit_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_task_event_deliveries_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE
        );

        -- Positions
        CREATE TABLE public.positions (
            position_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL
        );

        -- Departments
        CREATE TABLE public.departments (
            department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL
        );

        -- Employees
        CREATE TABLE public.employees (
            employee_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            full_name TEXT NOT NULL,
            department_id BIGINT NULL,
            position_id BIGINT NULL,
            date_from DATE NULL,
            date_to DATE NULL,
            employment_rate NUMERIC NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            org_unit_id BIGINT NULL,
            CONSTRAINT fk_employees_department FOREIGN KEY (department_id) REFERENCES public.departments(department_id),
            CONSTRAINT fk_employees_position FOREIGN KEY (position_id) REFERENCES public.positions(position_id),
            CONSTRAINT fk_employees_org_unit FOREIGN KEY (org_unit_id) REFERENCES public.org_units(unit_id)
        );

        -- Task audit log (task-specific)
        CREATE TABLE public.task_audit_log (
            audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            task_id BIGINT NULL,
            actor_user_id BIGINT NULL,
            action TEXT NULL,
            fields_changed JSONB NULL,
            request_body JSONB NULL,
            meta JSONB NULL,
            event_type TEXT NULL,
            actor_id BIGINT NULL,
            actor_role TEXT NULL,
            payload JSONB NULL,
            CONSTRAINT fk_task_audit_log_task
                FOREIGN KEY (task_id)
                REFERENCES public.tasks(task_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_task_audit_log_actor
                FOREIGN KEY (actor_user_id)
                REFERENCES public.users(user_id)
                ON DELETE SET NULL
        );

        -- Org unit managers
        CREATE TABLE public.org_unit_managers (
            manager_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            unit_id BIGINT NOT NULL,
            user_id BIGINT NOT NULL,
            manager_type TEXT NOT NULL,
            date_from DATE NULL,
            date_to DATE NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            CONSTRAINT fk_org_unit_managers_unit
                FOREIGN KEY (unit_id)
                REFERENCES public.org_units(unit_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_org_unit_managers_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE
        );

        CREATE UNIQUE INDEX ux_org_unit_managers_one_head
        ON public.org_unit_managers (unit_id)
        WHERE manager_type = 'HEAD' AND is_active = TRUE;

        -- User org units (many-to-many)
        CREATE TABLE public.user_org_units (
            user_id BIGINT NOT NULL,
            unit_id BIGINT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            PRIMARY KEY (user_id, unit_id),
            CONSTRAINT fk_user_org_units_user
                FOREIGN KEY (user_id)
                REFERENCES public.users(user_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_user_org_units_unit
                FOREIGN KEY (unit_id)
                REFERENCES public.org_units(unit_id)
                ON DELETE CASCADE
        );

        -- Org unit groups
        CREATE TABLE public.org_unit_groups (
            group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            deputy_user_id BIGINT NULL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT fk_org_unit_groups_deputy
                FOREIGN KEY (deputy_user_id)
                REFERENCES public.users(user_id)
                ON DELETE SET NULL
        );

        -- Org unit group units
        CREATE TABLE public.org_unit_group_units (
            group_id BIGINT NOT NULL,
            unit_id BIGINT NOT NULL,
            PRIMARY KEY (group_id, unit_id),
            CONSTRAINT fk_org_unit_group_units_group
                FOREIGN KEY (group_id)
                REFERENCES public.org_unit_groups(group_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_org_unit_group_units_unit
                FOREIGN KEY (unit_id)
                REFERENCES public.org_units(unit_id)
                ON DELETE CASCADE
        );

        -- Regular task runs
        CREATE TABLE public.regular_task_runs (
            run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ NULL,
            status TEXT NOT NULL,
            stats JSONB NOT NULL DEFAULT '{}'::jsonb,
            errors JSONB NOT NULL DEFAULT '[]'::jsonb
        );

        -- Regular task run items
        CREATE TABLE public.regular_task_run_items (
            item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL,
            regular_task_id BIGINT NULL,
            status TEXT NOT NULL,
            stats JSONB NOT NULL DEFAULT '{}'::jsonb,
            errors JSONB NOT NULL DEFAULT '[]'::jsonb,
            started_at TIMESTAMPTZ NULL,
            finished_at TIMESTAMPTZ NULL,
            period_id BIGINT NULL,
            executor_role_id BIGINT NULL,
            is_due BOOLEAN NULL,
            created_tasks INTEGER NOT NULL DEFAULT 0,
            error TEXT NULL,
            meta JSONB NOT NULL DEFAULT '{}'::jsonb,
            CONSTRAINT fk_regular_task_run_items_run
                FOREIGN KEY (run_id)
                REFERENCES public.regular_task_runs(run_id)
                ON DELETE CASCADE,
            CONSTRAINT fk_regular_task_run_items_regular
                FOREIGN KEY (regular_task_id)
                REFERENCES public.regular_tasks(regular_task_id)
                ON DELETE SET NULL,
            CONSTRAINT fk_regular_task_run_items_period
                FOREIGN KEY (period_id)
                REFERENCES public.reporting_periods(period_id)
                ON DELETE SET NULL,
            CONSTRAINT fk_regular_task_run_items_executor_role
                FOREIGN KEY (executor_role_id)
                REFERENCES public.roles(role_id)
                ON DELETE SET NULL
        );

        -- Staging/import tables (minimal)
        CREATE TABLE public.stg_import_org_units (
            unit_code TEXT,
            display_name_ru TEXT,
            parent_unit_code TEXT,
            is_active BOOLEAN
        );

        CREATE TABLE public.stg_import_roles (
            role_code TEXT,
            display_name_ru TEXT,
            is_active BOOLEAN,
            notes TEXT
        );

        CREATE TABLE public.stg_import_reports (
            report_code TEXT,
            display_name_ru TEXT,
            owner_unit_code TEXT,
            periodicity TEXT,
            executor_role_code TEXT,
            reviewer_role_code TEXT,
            is_active BOOLEAN,
            description TEXT,
            sample_link TEXT,
            tags TEXT
        );

        CREATE TABLE public.employees_import_stage (
            full_name TEXT,
            employee_id BIGINT,
            position_name TEXT,
            department_name TEXT,
            date_from DATE,
            date_to DATE,
            employment_rate NUMERIC,
            is_active BOOLEAN
        );

        CREATE TABLE public.employees_import (
            full_name TEXT,
            employee_id BIGINT,
            position_name TEXT,
            department_name TEXT,
            date_from DATE,
            date_to DATE,
            is_active BOOLEAN
        );

        -- db_schema_snapshot helper (as in repo)
        CREATE TABLE public.db_schema_snapshot (
            snapshot_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            table_name TEXT NOT NULL,
            column_name TEXT NOT NULL,
            data_type TEXT NOT NULL
        );

        -- Indexes
        CREATE INDEX idx_users_role_id ON public.users(role_id);
        CREATE INDEX idx_users_unit_id ON public.users(unit_id);

        CREATE INDEX idx_tasks_executor_role_id ON public.tasks(executor_role_id);
        CREATE INDEX idx_tasks_status_id ON public.tasks(status_id);
        CREATE INDEX idx_tasks_period_id ON public.tasks(period_id);

        CREATE INDEX idx_task_event_deliveries_user_status ON public.task_event_deliveries(user_id, status);
        CREATE INDEX idx_task_event_recipients_user ON public.task_event_recipients(user_id);
        """
    )


def downgrade() -> None:
    # Fast reset to empty public schema
    op.execute(
        """
        DROP SCHEMA IF EXISTS public CASCADE;
        CREATE SCHEMA public;
        GRANT ALL ON SCHEMA public TO public;
        """
    )