"""deps_group foundation — reference table, canonical seed, org_units FK.

Revision ID: a0b1c2d3e4f6
Revises: z8a9b0c1d2e3
"""
from __future__ import annotations

from alembic import op

revision = "a0b1c2d3e4f6"
down_revision = "z8a9b0c1d2e3"
branch_labels = None
depends_on = None

_CANONICAL_GROUPS: tuple[tuple[int, str], ...] = (
    (1, "Клинические"),
    (2, "Параклинические"),
    (3, "Административно-хозяйственные"),
)


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.deps_group (
            group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            group_name TEXT NOT NULL
        )
        """
    )

    op.execute(
        """
        DO $$
        DECLARE
            v_group_id_type text;
            v_group_id_nullable text;
            v_group_name_type text;
            v_group_name_nullable text;
        BEGIN
            IF to_regclass('public.deps_group') IS NULL THEN
                RAISE EXCEPTION 'deps_group table is missing after CREATE TABLE IF NOT EXISTS';
            END IF;

            SELECT c.data_type, c.is_nullable
            INTO v_group_id_type, v_group_id_nullable
            FROM information_schema.columns c
            WHERE c.table_schema = 'public'
              AND c.table_name = 'deps_group'
              AND c.column_name = 'group_id';

            IF v_group_id_type IS NULL THEN
                RAISE EXCEPTION
                    'deps_group exists but required column group_id is missing';
            END IF;

            IF v_group_id_type NOT IN ('bigint', 'integer', 'smallint') THEN
                RAISE EXCEPTION
                    'deps_group.group_id has incompatible type % (expected bigint/integer)',
                    v_group_id_type;
            END IF;

            IF v_group_id_nullable <> 'NO' THEN
                RAISE EXCEPTION 'deps_group.group_id must be NOT NULL';
            END IF;

            SELECT c.data_type, c.is_nullable
            INTO v_group_name_type, v_group_name_nullable
            FROM information_schema.columns c
            WHERE c.table_schema = 'public'
              AND c.table_name = 'deps_group'
              AND c.column_name = 'group_name';

            IF v_group_name_type IS NULL THEN
                RAISE EXCEPTION
                    'deps_group exists but required column group_name is missing';
            END IF;

            IF v_group_name_type NOT IN ('text', 'character varying') THEN
                RAISE EXCEPTION
                    'deps_group.group_name has incompatible type % (expected text)',
                    v_group_name_type;
            END IF;

            IF v_group_name_nullable <> 'NO' THEN
                RAISE EXCEPTION 'deps_group.group_name must be NOT NULL';
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_index idx
                JOIN pg_class tbl ON tbl.oid = idx.indrelid
                JOIN pg_namespace nsp ON nsp.oid = tbl.relnamespace
                WHERE nsp.nspname = 'public'
                  AND tbl.relname = 'deps_group'
                  AND idx.indisunique
                  AND idx.indnatts = 1
                  AND idx.indkey[0] = (
                      SELECT a.attnum
                      FROM pg_attribute a
                      WHERE a.attrelid = tbl.oid
                        AND a.attname = 'group_id'
                        AND NOT a.attisdropped
                  )
            ) THEN
                RAISE EXCEPTION
                    'deps_group.group_id must be PRIMARY KEY or have a UNIQUE constraint/index on group_id alone';
            END IF;
        END
        $$
        """
    )

    values_sql = ",\n            ".join(
        f"({group_id}, '{group_name.replace(chr(39), chr(39) * 2)}')"
        for group_id, group_name in _CANONICAL_GROUPS
    )
    op.execute(
        f"""
        INSERT INTO public.deps_group (group_id, group_name)
        VALUES
            {values_sql}
        ON CONFLICT (group_id) DO NOTHING
        """
    )

    op.execute(
        """
        DO $$
        DECLARE
            v_seq_name text;
            v_max_id bigint;
        BEGIN
            v_seq_name := pg_get_serial_sequence('public.deps_group', 'group_id');
            IF v_seq_name IS NULL THEN
                RETURN;
            END IF;

            SELECT COALESCE(MAX(group_id), 0)
            INTO v_max_id
            FROM public.deps_group;

            IF v_max_id <= 0 THEN
                PERFORM setval(v_seq_name::regclass, 1, false);
            ELSE
                PERFORM setval(v_seq_name::regclass, v_max_id, true);
            END IF;
        END
        $$
        """
    )

    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = 'org_units'
                  AND column_name = 'group_id'
            ) THEN
                RETURN;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'public.org_units'::regclass
                  AND conname = 'fk_org_units_group'
            ) THEN
                ALTER TABLE public.org_units
                    ADD CONSTRAINT fk_org_units_group
                        FOREIGN KEY (group_id)
                        REFERENCES public.deps_group (group_id);
            END IF;
        END
        $$
        """
    )


def downgrade() -> None:
    # Downgrade policy (ADR-ORG-GROUP-001 / reference-data safety):
    # - Drop only the FK introduced by this revision. Live/VPS databases may
    #   already rely on org_units.group_id → deps_group even when the FK was
    #   created outside Alembic.
    # - Never DROP deps_group here: downstream migrations (b0c1 personnel
    #   visibility, q7r8 personnel_applications) and operator data depend on
    #   it; removing the table would break FK chains or destroy synced
    #   reference rows.
    op.execute(
        """
        ALTER TABLE public.org_units
            DROP CONSTRAINT IF EXISTS fk_org_units_group
        """
    )
