"""add directory contacts table and positions category

Revision ID: f8c2a91b4e10
Revises: a7c4e1f903de
Create Date: 2026-06-09 07:30:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f8c2a91b4e10"
down_revision: Union[str, Sequence[str], None] = "a7c4e1f903de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS public.contacts (
            contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            person_id BIGINT NULL,
            full_name TEXT NOT NULL,
            phone TEXT NULL,
            telegram_username TEXT NULL,
            telegram_numeric_id BIGINT NULL,
            is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
        """
    )

    op.execute(
        """
        ALTER TABLE public.positions
        ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'other'
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        """
        ALTER TABLE public.positions
        DROP COLUMN IF EXISTS category
        """
    )

    op.execute(
        """
        DROP TABLE IF EXISTS public.contacts
        """
    )
