"use client";
import * as React from "react";
import { useRouter } from "next/navigation";
import { applyPersonLink, runPersonLinkPreflight, type PersonLinkPreflight } from "../_lib/personnelMigrationApi.client";
import type { NormalizedRecord } from "../_lib/importApi.client";

type Props = { employeeId: number; employeeName: string; iin: string; records: NormalizedRecord[]; preflight: PersonLinkPreflight; onClose: () => void };
export default function PersonLinkDialog({ employeeId, employeeName, iin, records, preflight, onClose }: Props) {
  const router = useRouter();
  const [selected, setSelected] = React.useState<number[]>(records.filter(r => r.employee_id === employeeId && r.iin === iin && r.review_status === "approved").map(r => r.normalized_record_id));
  const [currentPreflight, setCurrentPreflight] = React.useState(preflight);
  const [confirm, setConfirm] = React.useState(false); const [busy, setBusy] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const newName = currentPreflight.control_list_full_name || employeeName; const changed = newName !== employeeName;
  const valid = records.filter(r => r.employee_id === employeeId && r.iin === iin && r.review_status === "approved");
  async function toggle(id: number) { const next = selected.includes(id) ? selected.filter(x => x !== id) : [...selected, id]; setSelected(next); if (!next.length) return; const first = records[0]; try { setCurrentPreflight(await runPersonLinkPreflight(iin, { batch_id: first.batch_id, row_id: first.row_id, normalized_record_ids: next })); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось обновить preflight"); } }
  async function submit() { if (busy || !selected.length || currentPreflight.blockers.length || (changed && !confirm)) return; setBusy(true); setError(null); try { const result = await applyPersonLink({ employee_id: employeeId, normalized_record_ids: selected, expected_precondition: currentPreflight.expected_precondition || "", request_id: `adr065-${employeeId}-${selected.slice().sort().join("-")}`, confirm_name_correction: changed && confirm }); router.replace(`/directory/personnel/persons/${result.person_id}/card`); } catch (e) { setError(e instanceof Error ? e.message : "Не удалось создать рабочую личную карточку"); setBusy(false); } }
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-xl bg-white p-6 shadow-xl dark:bg-zinc-950"><div className="flex justify-between"><h2 className="text-lg font-semibold">Рабочая личная карточка</h2><button onClick={onClose}>Закрыть</button></div><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><div><dt>Employee</dt><dd>{employeeId}</dd></div><div><dt>ФИО</dt><dd>{employeeName}</dd></div><div><dt>ИИН</dt><dd>••••••{iin.slice(-4)}</dd></div><div><dt>Решение</dt><dd>{currentPreflight.classification === "P1_ADOPT" ? "ADOPT" : "CREATE"}</dd></div></dl><p className="mt-3 text-xs">Precondition: {currentPreflight.expected_precondition || "—"}</p><h3 className="mt-4 font-medium">Нормализованные записи</h3><ul className="mt-2 space-y-2">{records.map(r => <li key={r.normalized_record_id} className="flex gap-2 text-sm"><input type="checkbox" checked={selected.includes(r.normalized_record_id)} disabled={!valid.some(v => v.normalized_record_id === r.normalized_record_id)} onChange={() => void toggle(r.normalized_record_id)} /><span>#{r.normalized_record_id} · {r.record_kind} · {r.review_status} · {r.source_field}</span></li>)}</ul>{changed ? <section className="mt-4 rounded border border-amber-300 p-3 text-sm"><div>Текущее ФИО: {employeeName}</div><div>Новое ФИО: {newName}</div><label className="mt-2 flex gap-2"><input type="checkbox" checked={confirm} onChange={e => setConfirm(e.target.checked)} />Подтверждаю исправление ФИО</label></section> : null}{currentPreflight.blockers.length ? <div className="mt-4 rounded border border-red-300 p-3 text-sm">{currentPreflight.blockers.map(b => <div key={b.code}>{b.code}: {b.detail}</div>)}</div> : null}{error ? <p className="mt-3 text-sm text-red-700">{error}</p> : null}<div className="mt-5 flex gap-2"><button disabled={busy || !selected.length || !!currentPreflight.blockers.length || (changed && !confirm)} onClick={() => void submit()} className="rounded bg-blue-600 px-4 py-2 text-sm text-white disabled:opacity-50">{busy ? "Сохранение…" : "Подтвердить"}</button><button onClick={onClose} className="rounded border px-4 py-2 text-sm">Отмена</button></div></div></div>;
}
