"use client";

import * as React from "react";
import { PERSONNEL_ORDER_CREATE_TYPE_OPTIONS, createManualPersonnelOrderDraft, mapPersonnelOrdersApiError, previewPersonnelOrderHeaderDuplicate, type PersonnelOrderManualDraftCreateResult } from "../_lib/personnelOrdersApi.client";
import { getEmployees } from "@/app/directory/employees/_lib/api.client";
import type { EmployeeDTO } from "@/app/directory/employees/_lib/types";

type Props = { open: boolean; onClose: () => void; onCreated: (result: PersonnelOrderManualDraftCreateResult) => void };
const clean = (value: string) => value.trim();

export default function PersonnelOrderCreateDialog({ open, onClose, onCreated }: Props) {
  const [number, setNumber] = React.useState(""); const [orderDate, setOrderDate] = React.useState(""); const [title, setTitle] = React.useState(""); const [locale, setLocale] = React.useState<"kk" | "ru">("kk"); const [itemType, setItemType] = React.useState("HIRE");
  const [employeeQuery, setEmployeeQuery] = React.useState(""); const [selectedEmployee, setSelectedEmployee] = React.useState<EmployeeDTO | null>(null); const [employeeMatches, setEmployeeMatches] = React.useState<EmployeeDTO[]>([]); const [searchingEmployees, setSearchingEmployees] = React.useState(false);
  const [manualSubject, setManualSubject] = React.useState(false); const [manualFullName, setManualFullName] = React.useState(""); const [manualOrgUnit, setManualOrgUnit] = React.useState(""); const [manualPosition, setManualPosition] = React.useState(""); const [manualSpecialty, setManualSpecialty] = React.useState("");
  const [documentOrgUnit, setDocumentOrgUnit] = React.useState(""); const [documentPosition, setDocumentPosition] = React.useState(""); const [documentSpecialty, setDocumentSpecialty] = React.useState(""); const [effectiveDate, setEffectiveDate] = React.useState(""); const [submitting, setSubmitting] = React.useState(false); const [error, setError] = React.useState<string | null>(null);
  const requestId = React.useRef(0); const wasOpen = React.useRef(false);
  const clearManual = React.useCallback(() => { setManualSubject(false); setManualFullName(""); setManualOrgUnit(""); setManualPosition(""); setManualSpecialty(""); }, []);
  const clearDocumentContext = React.useCallback(() => { setDocumentOrgUnit(""); setDocumentPosition(""); setDocumentSpecialty(""); }, []);

  React.useEffect(() => {
    if (open && !wasOpen.current) { setNumber(""); setOrderDate(""); setTitle(""); setLocale("kk"); setItemType("HIRE"); setEmployeeQuery(""); setSelectedEmployee(null); setEmployeeMatches([]); clearManual(); clearDocumentContext(); setEffectiveDate(""); setError(null); }
    wasOpen.current = open;
  }, [clearDocumentContext, clearManual, open]);
  React.useEffect(() => {
    const query = employeeQuery.trim();
    if (manualSubject || selectedEmployee || query.length < 2) { setEmployeeMatches([]); setSearchingEmployees(false); return; }
    const id = ++requestId.current; setSearchingEmployees(true);
    void getEmployees({ q: query, status: "active", limit: 10, offset: 0 }).then((result) => { if (id === requestId.current) setEmployeeMatches(result.items); }).catch(() => { if (id === requestId.current) setEmployeeMatches([]); }).finally(() => { if (id === requestId.current) setSearchingEmployees(false); });
  }, [employeeQuery, manualSubject, selectedEmployee]);
  if (!open) return null;

  const chooseEmployee = (employee: EmployeeDTO) => { setSelectedEmployee(employee); setEmployeeQuery(employee.fio || ""); setEmployeeMatches([]); setDocumentPosition(employee.position?.name || ""); setDocumentOrgUnit(employee.org_unit?.name || ""); setDocumentSpecialty(""); };
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setSubmitting(true); setError(null);
    try {
      if (!selectedEmployee?.id && !manualSubject) { setError("Выберите сотрудника из списка или укажите его вручную."); return; }
      if (manualSubject && ![manualFullName, manualOrgUnit, manualPosition, manualSpecialty].every(clean)) { setError("Заполните ФИО, отделение, должность и специальность вручную."); return; }
      const duplicate = await previewPersonnelOrderHeaderDuplicate({ order_number: number, order_date: orderDate });
      if (duplicate.blocking) { setError("Найден приказ с таким же номером и датой."); return; }
      if (duplicate.warnings.length && !window.confirm("Есть приказ с тем же номером и другой датой. Продолжить?")) return;
      const result = await createManualPersonnelOrderDraft({ order_number: number, order_date: orderDate, source_title: title, source_title_locale: locale, item_type_code: itemType, employee_id: selectedEmployee?.id ? Number(selectedEmployee.id) : null, document_subject_context: selectedEmployee ? { org_unit_name: clean(documentOrgUnit) || null, position_name: clean(documentPosition) || null, specialty: clean(documentSpecialty) || null } : undefined, unresolved_subject: manualSubject ? { full_name: clean(manualFullName), org_unit_name: clean(manualOrgUnit), position_name: clean(manualPosition), specialty: clean(manualSpecialty) } : undefined, effective_date: effectiveDate });
      onCreated(result); onClose();
    } catch (err) { setError(mapPersonnelOrdersApiError(err, "Не удалось создать приказ.")); } finally { setSubmitting(false); }
  }
  const selectedView = selectedEmployee ? <div className="space-y-2"><div className="flex gap-2"><input aria-label="Сотрудник" readOnly value={selectedEmployee.fio || ""} className="min-w-0 flex-1 rounded border border-zinc-300 bg-zinc-50 p-2" /><button type="button" aria-label="Очистить выбранного сотрудника" className="text-sm text-blue-700 underline" onClick={() => { setSelectedEmployee(null); clearDocumentContext(); setEmployeeQuery(""); }}>Очистить</button></div><p className="text-sm text-zinc-600">{selectedEmployee.position?.name || "Должность не указана"} · {selectedEmployee.org_unit?.name || "Отделение не указано"}</p><input aria-label="Должность в приказе" value={documentPosition} onChange={(e) => setDocumentPosition(e.target.value)} placeholder="Должность в приказе" className="w-full rounded border p-2" /><input aria-label="Отделение в приказе" value={documentOrgUnit} onChange={(e) => setDocumentOrgUnit(e.target.value)} placeholder="Отделение в приказе" className="w-full rounded border p-2" /><input aria-label="Специальность" value={documentSpecialty} onChange={(e) => setDocumentSpecialty(e.target.value)} placeholder="Специальность" className="w-full rounded border p-2" /></div> : null;
  const manualView = <div className="space-y-2 rounded border border-amber-200 bg-amber-50 p-3"><p className="text-sm text-amber-900">Фигурант не привязан к справочнику и потребует последующей привязки.</p><input aria-label="ФИО вручную" required value={manualFullName} onChange={(e) => setManualFullName(e.target.value)} placeholder="ФИО" className="w-full rounded border p-2" /><input aria-label="Отделение вручную" required value={manualOrgUnit} onChange={(e) => setManualOrgUnit(e.target.value)} placeholder="Отделение" className="w-full rounded border p-2" /><input aria-label="Должность вручную" required value={manualPosition} onChange={(e) => setManualPosition(e.target.value)} placeholder="Должность" className="w-full rounded border p-2" /><input aria-label="Специальность вручную" required value={manualSpecialty} onChange={(e) => setManualSpecialty(e.target.value)} placeholder="Специальность" className="w-full rounded border p-2" /><button type="button" className="text-sm text-blue-700 underline" onClick={() => { clearManual(); setEmployeeQuery(""); }}>Вернуться к поиску</button></div>;
  const searchView = <><input aria-label="Сотрудник" autoComplete="off" value={employeeQuery} onChange={(e) => { setEmployeeQuery(e.target.value); setEmployeeMatches([]); }} placeholder="Начните вводить фамилию" className="w-full rounded border p-2" />{employeeQuery.trim().length >= 2 ? <div className="mt-1 rounded border border-zinc-200 bg-white" role="listbox" aria-label="Результаты поиска сотрудников">{searchingEmployees ? <p className="p-2 text-sm text-zinc-500">Поиск…</p> : employeeMatches.length ? employeeMatches.map((employee) => <button key={employee.id} type="button" role="option" className="block w-full border-b border-zinc-100 px-3 py-2 text-left last:border-b-0 hover:bg-blue-50" onClick={() => chooseEmployee(employee)}><span className="block font-medium">{employee.fio || "—"}</span><span className="block text-sm text-zinc-600">{employee.position?.name || "Должность не указана"} · {employee.org_unit?.name || "Отделение не указано"}</span></button>) : <div className="p-2"><p className="text-sm text-zinc-500">Сотрудники не найдены.</p><button type="button" className="mt-2 text-sm text-blue-700 underline" onClick={() => { setManualSubject(true); setManualFullName(employeeQuery); }}>Указать сотрудника вручную</button></div>}</div> : null}</>;
  return <div className="fixed inset-0 z-[60] flex items-center justify-center p-4" data-testid="personnel-order-create-dialog"><button type="button" aria-label="Закрыть" className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-md rounded-xl border border-zinc-200 bg-white p-5 shadow-xl"><h2 className="text-lg font-semibold">Создать приказ</h2><p className="mt-1 text-sm text-zinc-500">Ручной черновик с одним пунктом; кадровые последствия не создаются.</p><form className="mt-4 space-y-3" onSubmit={submit}><label className="block text-sm">Номер приказа<input aria-label="Номер приказа" required value={number} onChange={(e) => setNumber(e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Дата приказа<input aria-label="Дата приказа" type="date" required value={orderDate} onChange={(e) => setOrderDate(e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Исходное название<textarea aria-label="Исходное название" required value={title} onChange={(e) => setTitle(e.target.value)} className="mt-1 w-full rounded border p-2" /></label><label className="block text-sm">Язык исходного названия<select aria-label="Язык исходного названия" value={locale} onChange={(e) => setLocale(e.target.value as "kk" | "ru")} className="mt-1 w-full rounded border p-2"><option value="kk">Қазақша</option><option value="ru">Русский</option></select></label><label className="block text-sm">Тип пункта<select aria-label="Тип пункта" value={itemType} onChange={(e) => setItemType(e.target.value)} className="mt-1 w-full rounded border p-2">{PERSONNEL_ORDER_CREATE_TYPE_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label><div className="block text-sm">Сотрудник<div className="relative mt-1">{manualSubject ? manualView : selectedView || searchView}</div></div><label className="block text-sm">Дата действия<input aria-label="Дата действия" type="date" required value={effectiveDate} onChange={(e) => setEffectiveDate(e.target.value)} className="mt-1 w-full rounded border p-2" /></label>{error ? <p role="alert" className="text-sm text-red-700">{error}</p> : null}<div className="flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded border px-3 py-2 text-sm">Отмена</button><button type="submit" disabled={submitting} className="rounded bg-blue-600 px-3 py-2 text-sm text-white">{submitting ? "Создание…" : "Создать приказ"}</button></div></form></div></div>;
}
