"use client";

import * as React from "react";
import { getPersonnelReportOptions, getStaffingReport, type PersonnelReportOptions, type StaffingReport } from "../_lib/personnelReportsApi.client";

const iso = (d: Date) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
const yearStart = () => `${new Date().getFullYear()}-01-01`;
const monthOptions = () => Array.from({ length: new Date().getMonth() + 1 }, (_, i) => { const d = new Date(new Date().getFullYear(), new Date().getMonth() - i, 1); const from = iso(d); const to = iso(new Date(d.getFullYear(), d.getMonth() + 1, 0)); return { id: `${from}:${to}`, label: d.toLocaleDateString("ru-RU", { month: "long", year: "numeric" }), from, to }; });

export default function PersonnelStaffingReport() {
  const today = iso(new Date()); const [from, setFrom] = React.useState(yearStart); const [to, setTo] = React.useState(today); const [period, setPeriod] = React.useState("ytd");
  const [options, setOptions] = React.useState<PersonnelReportOptions>({ groups: [], departments: [] }); const [group, setGroup] = React.useState(""); const [unit, setUnit] = React.useState(""); const [breakdown, setBreakdown] = React.useState<"total" | "groups" | "units">("total"); const [report, setReport] = React.useState<StaffingReport | null>(null); const [open, setOpen] = React.useState<"hired" | "terminated" | null>(null);
  React.useEffect(() => { void getPersonnelReportOptions().then(setOptions); }, []);
  React.useEffect(() => { if (!from || !to) return; void getStaffingReport({ dateFrom: from, dateTo: to, groupId: group ? Number(group) : undefined, orgUnitId: unit ? Number(unit) : undefined, breakdown }).then(setReport); }, [from, to, group, unit, breakdown]);
  const departments = options.departments.filter((x) => !group || String(x.group_id) === group);
  const setDates = (nextFrom: string, nextTo: string, id: string) => { setFrom(nextFrom); setTo(nextTo); setPeriod(id); };
  return <div className="space-y-5 px-4 py-5"><header><h2 className="text-xl font-semibold">Отчёты по кадровому составу</h2><p className="mt-1 text-sm text-zinc-600 dark:text-zinc-400">Показатели численности и движения работников за выбранный период</p></header>
    <section className="grid gap-3 rounded-xl border border-zinc-200 p-4 md:grid-cols-2 xl:grid-cols-5 dark:border-zinc-800"><label className="text-sm">Период<select aria-label="Период" className="mt-1 w-full rounded border p-2" value={period} onChange={e => { const value=e.target.value; if(value==="ytd") setDates(yearStart(), today, value); else if(value!=="custom"){const found=monthOptions().find(x=>x.id===value); if(found) setDates(found.from,found.to,value)} else setPeriod(value); }}><option value="ytd">С начала года</option>{monthOptions().map(x=><option key={x.id} value={x.id}>{x.label}</option>)}<option value="custom">Произвольный период</option></select></label><label className="text-sm">Дата с<input aria-label="Дата с" type="date" className="mt-1 w-full rounded border p-2" value={from} onChange={e=>{setFrom(e.target.value);setPeriod("custom")}} /></label><label className="text-sm">Дата по<input aria-label="Дата по" type="date" className="mt-1 w-full rounded border p-2" value={to} onChange={e=>{setTo(e.target.value);setPeriod("custom")}} /></label><label className="text-sm">Группа отделений<select aria-label="Группа отделений" className="mt-1 w-full rounded border p-2" value={group} onChange={e=>{setGroup(e.target.value);setUnit("")}}><option value="">Все группы отделений</option>{options.groups.map(x=><option key={x.group_id} value={x.group_id}>{x.group_name}</option>)}</select></label><label className="text-sm">Отделение<select aria-label="Отделение" className="mt-1 w-full rounded border p-2" value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Все отделения</option>{departments.map(x=><option key={x.unit_id} value={x.unit_id}>{x.unit_name}</option>)}</select></label></section>
    {report?.data_quality.requires_review ? <div role="alert" className="rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">{report.data_quality.message}</div> : null}
    {report ? <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Текущая численность", report.metrics.current_headcount], ["Принято работников", report.metrics.hired], ["Уволено работников", report.metrics.terminated], ["Среднесписочная численность", report.metrics.average_headcount], ["Текучесть кадров", `${report.metrics.turnover_percent}%`]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-4"><div className="text-sm text-zinc-500">{label}</div><div className="mt-1 text-2xl font-semibold">{value}</div>{label==="Принято работников"?<button className="mt-2 text-sm text-blue-700" onClick={()=>setOpen("hired")}>Открыть список</button>:label==="Уволено работников"?<button className="mt-2 text-sm text-blue-700" onClick={()=>setOpen("terminated")}>Открыть список</button>:null}</div>)}</section>
      <section className="rounded-xl border p-4 text-sm"><div>Среднесписочная численность: {report.metrics.average_formula}</div><div className="mt-2">Текучесть: {report.metrics.turnover_numerator} / {report.metrics.average_headcount} × 100% = {report.metrics.turnover_percent}%</div>{report.metrics.turnover_reasons.map(x=><div key={x.reason} className="mt-1">{x.reason}: {x.count}</div>)}</section>
      <section className="rounded-xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Разрез показателей</h3><select aria-label="Разрез показателей" value={breakdown} onChange={e=>setBreakdown(e.target.value as typeof breakdown)} className="rounded border p-2 text-sm"><option value="total">Общий итог</option><option value="groups">По группам отделений</option><option value="units">По отделениям</option></select></div><div className="mt-3 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th>Группа или отделение</th><th>Текущая</th><th>Среднесписочная</th><th>Принято</th><th>Уволено</th><th>По текучести</th><th>Текучесть, %</th></tr></thead><tbody>{(breakdown==="total"?[{label:"Общий итог",current_headcount:report.metrics.current_headcount,average_headcount:report.metrics.average_headcount,hired:report.metrics.hired,terminated:report.metrics.terminated,turnover_terminated:report.metrics.turnover_numerator,turnover_percent:report.metrics.turnover_percent}]:report.breakdown).map(x=><tr key={x.label} className="border-t"><td>{x.label}</td><td>{x.current_headcount}</td><td>{x.average_headcount}</td><td>{x.hired}</td><td>{x.terminated}</td><td>{x.turnover_terminated}</td><td>{x.turnover_percent}%</td></tr>)}</tbody></table></div></section>
      {open?<section className="rounded-xl border p-4"><div className="flex justify-between"><h3 className="font-semibold">{open==="hired"?"Принято работников":"Уволено работников"}</h3><button onClick={()=>setOpen(null)}>Закрыть</button></div><ul className="mt-3 space-y-2">{(open==="hired"?report.hired_items:report.terminated_items).map((x,i)=><li key={`${x.full_name}-${i}`}>{x.full_name} — {x.date}{"group_name" in x ? ` — ${x.group_name}, ${x.unit_name}` : ""}{"reason" in x?` — ${x.reason}`:""}</li>)}</ul></section>:null}</>:<div className="p-6 text-zinc-500">Загрузка…</div>}</div>;
}
