"use client";
import * as React from "react";
import { apiFetchJson } from "@/lib/api";
import type { PprQualificationCategoryRecordResponse } from "../_lib/pprQueryTypes";

type Row = PprQualificationCategoryRecordResponse;
export default function PprQualificationCategoryEditor({ personId, items, version, onSaved }: {personId:number;items:Row[];version:string;onSaved:()=>void}) {
 const [rows,setRows]=React.useState<Row[]>(items); const [saving,setSaving]=React.useState(false); const [error,setError]=React.useState<string|null>(null);
 const change=(i:number,key:keyof Row,value:string)=>setRows(rows.map((r,n)=>n===i?{...r,[key]:value}:r));
 async function save(){setSaving(true);setError(null);try{await apiFetchJson(`/directory/personnel/migration-status/persons/${personId}/qualification-categories`,{method:"PUT",body:{expected_version:version,qualification_categories:rows}});onSaved();}catch(e){setError(e instanceof Error?e.message:"Не удалось сохранить категорию.");}finally{setSaving(false)}}
 return <div className="space-y-3" data-testid="ppr-category-editor"><div className="overflow-x-auto"><table className="w-full min-w-[48rem] table-fixed"><colgroup><col className="w-auto"/><col className="w-36"/><col className="w-40"/><col className="w-24"/></colgroup><thead><tr><th>Специальность</th><th>Категория</th><th>Дата присвоения</th><th><span className="sr-only">Действия</span></th></tr></thead><tbody>{rows.map((row,i)=><tr key={row.source_fingerprint??i}><td className="pr-2"><input aria-label={`Специальность ${i+1}`} value={row.specialty} onChange={e=>change(i,"specialty",e.target.value)} className="w-full min-w-0 rounded border p-1"/></td><td><select aria-label={`Категория ${i+1}`} value={row.category} onChange={e=>change(i,"category",e.target.value)} className="w-full rounded border p-1"><option value="highest">Высшая</option><option value="first">Первая</option><option value="second">Вторая</option></select></td><td><input aria-label={`Дата присвоения ${i+1}`} type="date" value={row.assigned_at} onChange={e=>change(i,"assigned_at",e.target.value)} className="w-full rounded border p-1"/></td><td><button type="button" onClick={()=>setRows(rows.filter((_,n)=>n!==i))}>Удалить</button></td></tr>)}</tbody></table></div><div className="flex gap-2"><button type="button" onClick={()=>setRows([...rows,{specialty:"",category:"highest",assigned_at:"",assigned_at_calculated:false,review_status:"REVIEW_REQUIRED",review_reason:null,source_fingerprint:null}])}>Добавить строку</button><button type="button" onClick={()=>void save()} disabled={saving}>{saving?"Сохранение…":"Сохранить"}</button></div>{error?<p role="alert">{error}</p>:null}</div>
}
