"""Inventory and scope boundaries for WP-CL-010 other PPR normalization."""
from __future__ import annotations

from app.control_list_import.domain.vocabulary import (
    SEMANTIC_FIELD_CONTACT_EMAIL,
    SEMANTIC_FIELD_CONTACT_PHONE,
    SEMANTIC_FIELD_CONTACT_REGISTRATION_ADDRESS,
    SEMANTIC_FIELD_CONTACT_RESIDENCE_ADDRESS,
    SEMANTIC_FIELD_EDUCATION_RECORDS,
    SEMANTIC_FIELD_EMPLOYMENT_DEPARTMENT_NAME,
    SEMANTIC_FIELD_EMPLOYMENT_POSITION_TITLE,
    SEMANTIC_FIELD_EMPLOYMENT_RATE,
    SEMANTIC_FIELD_EMPLOYMENT_STARTED_AT,
    SEMANTIC_FIELD_PERSON_AWARDS,
    SEMANTIC_FIELD_PERSON_BIRTH_DATE,
    SEMANTIC_FIELD_PERSON_CITIZENSHIP,
    SEMANTIC_FIELD_PERSON_FULL_NAME,
    SEMANTIC_FIELD_PERSON_IIN,
    SEMANTIC_FIELD_PERSON_NATIONALITY_RAW,
    SEMANTIC_FIELD_PERSON_NOTES,
    SEMANTIC_FIELD_PERSON_PHONE,
    SEMANTIC_FIELD_PERSON_SEX,
    SEMANTIC_FIELD_PPR_DISABILITY_SUMMARY,
    SEMANTIC_FIELD_PPR_MARITAL_STATUS,
    SEMANTIC_FIELD_PPR_MILITARY_SUMMARY,
    SEMANTIC_FIELD_QUALIFICATION_CATEGORY,
    SEMANTIC_FIELD_QUALIFICATION_DEGREE,
    SEMANTIC_FIELD_TRAINING_RECORDS,
)

OTHER_PPR_SUPPORTED_FIELDS: frozenset[str] = frozenset(
    {
        SEMANTIC_FIELD_PERSON_CITIZENSHIP,
        SEMANTIC_FIELD_PERSON_NATIONALITY_RAW,
        SEMANTIC_FIELD_PPR_MARITAL_STATUS,
        SEMANTIC_FIELD_PPR_MILITARY_SUMMARY,
        SEMANTIC_FIELD_PPR_DISABILITY_SUMMARY,
        SEMANTIC_FIELD_PERSON_AWARDS,
        SEMANTIC_FIELD_PERSON_NOTES,
        SEMANTIC_FIELD_QUALIFICATION_CATEGORY,
        SEMANTIC_FIELD_QUALIFICATION_DEGREE,
    }
)

OTHER_PPR_EXCLUDED_FIELDS: frozenset[str] = frozenset(
    {
        SEMANTIC_FIELD_PERSON_FULL_NAME,
        SEMANTIC_FIELD_PERSON_BIRTH_DATE,
        SEMANTIC_FIELD_PERSON_IIN,
        SEMANTIC_FIELD_PERSON_SEX,
        SEMANTIC_FIELD_PERSON_PHONE,
        SEMANTIC_FIELD_EMPLOYMENT_DEPARTMENT_NAME,
        SEMANTIC_FIELD_EMPLOYMENT_POSITION_TITLE,
        SEMANTIC_FIELD_EMPLOYMENT_RATE,
        SEMANTIC_FIELD_EMPLOYMENT_STARTED_AT,
        SEMANTIC_FIELD_CONTACT_PHONE,
        SEMANTIC_FIELD_CONTACT_EMAIL,
        SEMANTIC_FIELD_CONTACT_RESIDENCE_ADDRESS,
        SEMANTIC_FIELD_CONTACT_REGISTRATION_ADDRESS,
        SEMANTIC_FIELD_EDUCATION_RECORDS,
        SEMANTIC_FIELD_TRAINING_RECORDS,
    }
)

OTHER_PPR_SKIP_REASON_BY_FIELD: dict[str, str] = {
    field: "handled_by_prior_control_list_work_package"
    for field in OTHER_PPR_EXCLUDED_FIELDS
}
