"""Reconciliation decision foundation (WP-PPR-CARD-COORDINATION-003)."""
from __future__ import annotations

from app.personnel_intake.domain.reconciliation.actions import (
    APPLY_STATUSES,
    APPLY_STATUS_APPLIED,
    APPLY_STATUS_BLOCKED,
    APPLY_STATUS_FAILED,
    APPLY_STATUS_PENDING,
    APPLY_STATUS_SKIPPED_MANUAL,
    DECISION_SOURCES,
    DECISION_SOURCE_HR,
    DECISION_SOURCE_SYSTEM,
    REASON_CODES,
    RECONCILE_ACTIONS,
    RECONCILE_ACTION_ADD,
    RECONCILE_ACTION_KEEP_EXISTING,
    RECONCILE_ACTION_MANUAL_REVIEW,
    RECONCILE_ACTION_SUPERSEDE,
    RECONCILE_ACTION_UPDATE_VERSION,
    SECTION_CODES,
)
from app.personnel_intake.domain.reconciliation.errors import (
    ReconciliationConflictError,
    ReconciliationConcurrencyError,
    ReconciliationError,
    ReconciliationNotFoundError,
    ReconciliationValidationError,
)
from app.personnel_intake.domain.reconciliation.invariants import (
    assert_valid_action,
    assert_valid_apply_status,
    assert_valid_batch_terminal_finalization,
    assert_valid_create,
    assert_valid_decision_evidence,
    assert_valid_reason_code,
    assert_valid_terminal_reason_code,
    assert_valid_transition,
    compute_intent_fingerprint,
    is_terminal_apply_status,
)
from app.personnel_intake.domain.reconciliation.digest import (
    DIGEST_ALGORITHM_CANON_JSON_V1,
    CanonJsonV1DigestBuilder,
    DEFAULT_DIGEST_BUILDER_REGISTRY,
    DigestBuilder,
    DigestBuilderRegistry,
)
from app.personnel_intake.domain.reconciliation.models import (
    BatchTerminalFinalizationCommand,
    BatchTerminalFinalizationResult,
    BatchTerminalTransitionItem,
    CreatePendingDecisionCommand,
    CreatePendingDecisionResult,
    ReconcileDecisionRecord,
    TerminalTransitionCommand,
)

__all__ = [
    "DIGEST_ALGORITHM_CANON_JSON_V1",
    "CanonJsonV1DigestBuilder",
    "DEFAULT_DIGEST_BUILDER_REGISTRY",
    "DigestBuilder",
    "DigestBuilderRegistry",
    "APPLY_STATUSES",
    "APPLY_STATUS_APPLIED",
    "APPLY_STATUS_BLOCKED",
    "APPLY_STATUS_FAILED",
    "APPLY_STATUS_PENDING",
    "APPLY_STATUS_SKIPPED_MANUAL",
    "BatchTerminalFinalizationCommand",
    "BatchTerminalFinalizationResult",
    "BatchTerminalTransitionItem",
    "CreatePendingDecisionCommand",
    "CreatePendingDecisionResult",
    "DECISION_SOURCES",
    "DECISION_SOURCE_HR",
    "DECISION_SOURCE_SYSTEM",
    "REASON_CODES",
    "RECONCILE_ACTIONS",
    "RECONCILE_ACTION_ADD",
    "RECONCILE_ACTION_KEEP_EXISTING",
    "RECONCILE_ACTION_MANUAL_REVIEW",
    "RECONCILE_ACTION_SUPERSEDE",
    "RECONCILE_ACTION_UPDATE_VERSION",
    "ReconcileDecisionRecord",
    "ReconciliationConflictError",
    "ReconciliationConcurrencyError",
    "ReconciliationError",
    "ReconciliationNotFoundError",
    "ReconciliationValidationError",
    "SECTION_CODES",
    "TerminalTransitionCommand",
    "assert_valid_action",
    "assert_valid_apply_status",
    "assert_valid_batch_terminal_finalization",
    "assert_valid_create",
    "assert_valid_decision_evidence",
    "assert_valid_reason_code",
    "assert_valid_terminal_reason_code",
    "assert_valid_transition",
    "compute_intent_fingerprint",
    "is_terminal_apply_status",
]
