"""MRD domain types and enums (ADR-058 / WP-MRD-001)."""
from __future__ import annotations

from app.db.models.hr_monthly_reference import (
    COMPARISON_RUN_CANCELLED,
    COMPARISON_RUN_COMPLETED,
    COMPARISON_RUN_FAILED,
    COMPARISON_RUN_RUNNING,
    DIFFERENCE_BUSINESS_NEVER_CONFIRMED,
    DIFFERENCE_BUSINESS_PERIOD_CHANGED,
    DIFFERENCE_LIFECYCLE_CONFIRMED,
    DIFFERENCE_LIFECYCLE_DETECTED,
    DIFFERENCE_LIFECYCLE_REJECTED,
    DIFFERENCE_LIFECYCLE_SUPERSEDED,
    MRD_COMMAND_EXECUTION_COMPLETED,
    MRD_COMMAND_EXECUTION_PENDING,
    MRD_COMMAND_FORK_PERIOD,
    MRD_COMMAND_FORK_VERSION,
    MRD_RECORD_KINDS,
    MRD_STATUS_ACTIVE,
    MRD_STATUS_CLOSED,
    ORIGIN_DATA_REPAIR,
    ORIGIN_IMPORT_COMPARE,
    ORIGIN_MANUAL_EDIT,
    ORIGIN_MRD_FORK,
    ORIGIN_SYSTEM_RECALC,
    REFERENCE_EVENT_ACTIVATE,
    REFERENCE_EVENT_CLOSE,
    REFERENCE_EVENT_CREATE,
    REFERENCE_EVENT_FORK_PERIOD,
    REFERENCE_EVENT_FORK_VERSION,
    SOURCE_TYPE_HR_CONTROL_LIST,
    TECHNICAL_DIFF_CHANGED,
    TECHNICAL_DIFF_CONFLICT,
    TECHNICAL_DIFF_NEW,
    TECHNICAL_DIFF_REMOVED,
)

MRD_STATUSES = frozenset({MRD_STATUS_ACTIVE, MRD_STATUS_CLOSED})

DIFFERENCE_LIFECYCLE_STATUSES = frozenset(
    {
        DIFFERENCE_LIFECYCLE_DETECTED,
        DIFFERENCE_LIFECYCLE_CONFIRMED,
        DIFFERENCE_LIFECYCLE_REJECTED,
        DIFFERENCE_LIFECYCLE_SUPERSEDED,
    }
)

TERMINAL_DIFFERENCE_LIFECYCLE_STATUSES = frozenset(
    {
        DIFFERENCE_LIFECYCLE_CONFIRMED,
        DIFFERENCE_LIFECYCLE_REJECTED,
        DIFFERENCE_LIFECYCLE_SUPERSEDED,
    }
)

DIFFERENCE_BUSINESS_TYPES = frozenset(
    {
        DIFFERENCE_BUSINESS_NEVER_CONFIRMED,
        DIFFERENCE_BUSINESS_PERIOD_CHANGED,
    }
)

TECHNICAL_DIFF_CLASSES = frozenset(
    {
        TECHNICAL_DIFF_NEW,
        TECHNICAL_DIFF_CHANGED,
        TECHNICAL_DIFF_REMOVED,
        TECHNICAL_DIFF_CONFLICT,
    }
)

SEED_DIFFERENCE_ORIGIN_CODES = frozenset(
    {
        ORIGIN_IMPORT_COMPARE,
        ORIGIN_MANUAL_EDIT,
        ORIGIN_SYSTEM_RECALC,
        ORIGIN_MRD_FORK,
        ORIGIN_DATA_REPAIR,
    }
)

COMPARISON_RUN_STATUSES = frozenset(
    {
        COMPARISON_RUN_RUNNING,
        COMPARISON_RUN_COMPLETED,
        COMPARISON_RUN_FAILED,
        COMPARISON_RUN_CANCELLED,
    }
)

REFERENCE_VERSION_EVENT_TYPES = frozenset(
    {
        REFERENCE_EVENT_FORK_VERSION,
        REFERENCE_EVENT_FORK_PERIOD,
        REFERENCE_EVENT_CLOSE,
        REFERENCE_EVENT_ACTIVATE,
        REFERENCE_EVENT_CREATE,
    }
)

MRD_COMMAND_TYPES = frozenset({MRD_COMMAND_FORK_VERSION, MRD_COMMAND_FORK_PERIOD})

__all__ = [
    "COMPARISON_RUN_CANCELLED",
    "COMPARISON_RUN_COMPLETED",
    "COMPARISON_RUN_FAILED",
    "COMPARISON_RUN_RUNNING",
    "COMPARISON_RUN_STATUSES",
    "DIFFERENCE_BUSINESS_NEVER_CONFIRMED",
    "DIFFERENCE_BUSINESS_PERIOD_CHANGED",
    "DIFFERENCE_BUSINESS_TYPES",
    "DIFFERENCE_LIFECYCLE_CONFIRMED",
    "DIFFERENCE_LIFECYCLE_DETECTED",
    "DIFFERENCE_LIFECYCLE_REJECTED",
    "DIFFERENCE_LIFECYCLE_SUPERSEDED",
    "DIFFERENCE_LIFECYCLE_STATUSES",
    "MRD_COMMAND_EXECUTION_COMPLETED",
    "MRD_COMMAND_EXECUTION_PENDING",
    "MRD_COMMAND_FORK_PERIOD",
    "MRD_COMMAND_FORK_VERSION",
    "MRD_COMMAND_TYPES",
    "MRD_RECORD_KINDS",
    "MRD_STATUS_ACTIVE",
    "MRD_STATUS_CLOSED",
    "MRD_STATUSES",
    "ORIGIN_DATA_REPAIR",
    "ORIGIN_IMPORT_COMPARE",
    "ORIGIN_MANUAL_EDIT",
    "ORIGIN_MRD_FORK",
    "ORIGIN_SYSTEM_RECALC",
    "REFERENCE_EVENT_ACTIVATE",
    "REFERENCE_EVENT_CLOSE",
    "REFERENCE_EVENT_CREATE",
    "REFERENCE_EVENT_FORK_PERIOD",
    "REFERENCE_EVENT_FORK_VERSION",
    "REFERENCE_VERSION_EVENT_TYPES",
    "SEED_DIFFERENCE_ORIGIN_CODES",
    "SOURCE_TYPE_HR_CONTROL_LIST",
    "TECHNICAL_DIFF_CHANGED",
    "TECHNICAL_DIFF_CLASSES",
    "TECHNICAL_DIFF_CONFLICT",
    "TECHNICAL_DIFF_NEW",
    "TECHNICAL_DIFF_REMOVED",
    "TERMINAL_DIFFERENCE_LIFECYCLE_STATUSES",
]
