"use client";

import { useEffect, useState } from "react";
import { apiFetchJson } from "@/lib/api";

type Classification = "CONFIRMED_TECHNICAL" | "LEGACY_TECHNICAL_CANDIDATE";
type Employee = { employee_id: number; order_snapshot?: { employee_name?: string; payload?: Record<string, unknown> }; current_personnel_data?: { status?: string; department?: string | null; position?: string | null } };
type Order = { order_id: number; order_number?: string | null; order_date?: string | null; order_type_code: string; status: string; employees?: string[]; employee_details?: Employee[]; import_source_id?: string | null; classification: Classification; dependency_check?: "REQUIRES_CHECK" };
type Preview = { classification: Classification; can_delete: boolean; can_confirm_provenance?: boolean; confirmation_phrase: string; planned_deletions: { table: string; count: number }[]; blocking_dependencies: { table: string; count: number }[] };
type BatchPreview = { ready: { order_id: number }[]; legacy: { order_id: number }[]; blocked: { order_id: number; reason: string }[]; confirmation_phrase: string; can_execute: boolean; planned_deletions: { table: string; count: number }[] };
type ListResponse = { items: Order[]; page: number; page_size: number; total: number };

const endpoint = "/directory/technical-personnel-order-cleanup";
const label = (order: Order) => order.classification === "CONFIRMED_TECHNICAL" ? "Техническая запись" : "Техническая запись прежнего формата";

export default function TechnicalPersonnelOrdersPanel() {
  const [query, setQuery] = useState(""); const [field, setField] = useState("q"); const [items, setItems] = useState<Order[]>([]); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(25); const [total, setTotal] = useState(0);
  const [selectedIds, setSelectedIds] = useState<number[]>([]); const [preview, setPreview] = useState<Preview | null>(null); const [batch, setBatch] = useState<BatchPreview | null>(null); const [selected, setSelected] = useState<Order | null>(null); const [mode, setMode] = useState<"delete" | "confirm">("delete"); const [reason, setReason] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState("");
  const showError = (error: unknown) => setMessage(error instanceof Error ? error.message : "Не удалось выполнить операцию.");
  async function load(nextPage = page) { setMessage(""); setSelectedIds([]); try { const params = new URLSearchParams({ page: String(nextPage), page_size: String(pageSize) }); if (query.trim()) params.set(field, query.trim()); const response = await apiFetchJson(`${endpoint}/search?${params}`) as ListResponse; setItems(Array.isArray(response.items) ? response.items : []); setPage(response.page || nextPage); setTotal(response.total || 0); } catch (error) { showError(error); } }
  useEffect(() => { void load(1); // initial listing never asks for dependency previews
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pageSize]);
  async function inspect(order: Order, nextMode: "delete" | "confirm") { setMessage(""); setBatch(null); try { setSelected(order); setMode(nextMode); setPreview(await apiFetchJson(`${endpoint}/${order.order_id}/${nextMode === "confirm" ? "provenance-preview" : "preview"}`) as Preview); } catch (error) { showError(error); } }
  async function execute() { if (!selected || !reason.trim() || confirmation !== preview?.confirmation_phrase) { setMessage("Укажите причину и точную фразу подтверждения."); return; } try { const action = mode === "confirm" ? "confirm-provenance" : "execute"; const result = await apiFetchJson(`${endpoint}/${selected.order_id}/${action}`, { method: "POST", body: JSON.stringify({ reason, confirmation_phrase: confirmation }) }) as { status: string }; setMessage(`${mode === "confirm" ? "Происхождение подтверждено" : "Удаление завершено"}: ${result.status}`); await load(1); } catch (error) { showError(error); } }
  async function batchPreview() { if (!selectedIds.length || selectedIds.length > 25) { setMessage("Для batch-preview выберите от 1 до 25 приказов."); return; } setMessage(""); try { setPreview(null); setBatch(await apiFetchJson(`${endpoint}/batch-preview`, { method: "POST", body: JSON.stringify({ order_ids: selectedIds }) }) as BatchPreview); } catch (error) { showError(error); } }
  async function batchExecute() { if (!batch || !batch.can_execute || !reason.trim() || confirmation !== batch.confirmation_phrase) { setMessage("Укажите причину и точную фразу подтверждения batch-удаления."); return; } try { const result = await apiFetchJson(`${endpoint}/batch-execute`, { method: "POST", body: JSON.stringify({ order_ids: selectedIds, reason, confirmation_phrase: confirmation }) }) as { status: string }; setMessage(`Batch-удаление завершено: ${result.status}`); setBatch(null); await load(1); } catch (error) { showError(error); } }
  const selectable = items.filter((order) => order.classification === "CONFIRMED_TECHNICAL").map((order) => order.order_id);
  const allSelected = selectable.length > 0 && selectable.every((id) => selectedIds.includes(id));
  const toggle = (id: number) => setSelectedIds((ids) => ids.includes(id) ? ids.filter((value) => value !== id) : ids.length < 25 ? [...ids, id] : ids);
  return <section className="space-y-3" aria-label="Технические кадровые приказы"><p className="text-sm text-zinc-600 dark:text-zinc-400">Начальный список не выполняет проверку зависимостей: для каждой записи показано «Требует проверки».</p>
    <div className="flex flex-wrap gap-2"><select aria-label="Поле поиска технического приказа" className="rounded border p-2" value={field} onChange={(e) => setField(e.target.value)}><option value="order_id">Точный order_id</option><option value="q">Номер приказа</option><option value="employee_name">ФИО сотрудника</option><option value="import_source">Источник импорта</option></select><input aria-label="Поиск технического приказа" className="rounded border p-2" value={query} onChange={(e) => setQuery(e.target.value)} /><button className="rounded bg-blue-600 px-3 py-2 text-white" onClick={() => void load(1)}>Найти</button><label>Строк: <select aria-label="Размер страницы" value={pageSize} onChange={(e) => setPageSize(Number(e.target.value))}><option value={25}>25</option><option value={50}>50</option></select></label></div>
    <div className="flex items-center gap-3"><button type="button" className="rounded border px-3 py-2 disabled:opacity-50" disabled={!selectedIds.length} onClick={() => void batchPreview()}>Подготовить удаление выбранных</button><span role="status">Выбрано: {selectedIds.length} из 25</span>{selectedIds.length === 25 ? <span className="text-sm font-medium text-amber-700">Выбрано 25 — максимальный размер одной операции</span> : null}</div>
    <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th><input aria-label="Выбрать доступные на странице" type="checkbox" checked={allSelected} onChange={() => setSelectedIds(allSelected ? [] : selectable.slice(0, 25))} /></th><th>order_id</th><th>Номер приказа</th><th>Дата</th><th>Тип</th><th>Статус</th><th>Сотрудники</th><th>Класс записи</th><th>Источник импорта</th><th>Зависимости</th><th>Действия</th></tr></thead><tbody>{items.map((order) => <tr key={order.order_id} className="border-t"><td><input aria-label={`Выбрать приказ ${order.order_id}`} type="checkbox" disabled={order.classification !== "CONFIRMED_TECHNICAL" || (!selectedIds.includes(order.order_id) && selectedIds.length >= 25)} checked={selectedIds.includes(order.order_id)} onChange={() => toggle(order.order_id)} /></td><td>{order.order_id}</td><td>{order.order_number || "—"}</td><td>{order.order_date || "—"}</td><td>{order.order_type_code}</td><td>{order.status}</td><td><details><summary>{(order.employees || []).length} сотрудников</summary><p>Данные приказа — snapshot на момент создания:</p>{(order.employee_details || []).map((employee) => <div key={employee.employee_id}>ФИО: {employee.order_snapshot?.employee_name || "—"}. Текущие кадровые данные — {employee.current_personnel_data?.status || "—"}, {employee.current_personnel_data?.department || "—"}, {employee.current_personnel_data?.position || "—"}</div>)}</details></td><td>{label(order)}</td><td>{order.import_source_id || "—"}</td><td>{order.dependency_check === "REQUIRES_CHECK" ? "Требует проверки" : "—"}</td><td><button className="rounded border px-2 py-1" onClick={() => void inspect(order, "delete")}>Preview удаления</button>{order.classification === "LEGACY_TECHNICAL_CANDIDATE" ? <button className="ml-2 rounded border px-2 py-1" onClick={() => void inspect(order, "confirm")}>Подтвердить техническое происхождение</button> : null}</td></tr>)}</tbody></table></div>
    <div className="flex gap-2"><button disabled={page <= 1} onClick={() => void load(page - 1)}>Назад</button><span>Страница {page} из {Math.max(1, Math.ceil(total / pageSize))}</span><button disabled={page * pageSize >= total} onClick={() => void load(page + 1)}>Вперёд</button></div>
    {preview && selected ? <div className="space-y-2 rounded border border-amber-400 p-3"><h3 className="font-semibold">Preview #{selected.order_id}</h3><div>Блокеры: {preview.blocking_dependencies.length ? preview.blocking_dependencies.map((x) => `${x.table} (${x.count})`).join(", ") : "нет"}</div>{(mode === "confirm" ? preview.can_confirm_provenance : preview.can_delete) ? <><input aria-label="Причина операции" className="rounded border p-2" value={reason} onChange={(e) => setReason(e.target.value)} /><input aria-label="Фраза подтверждения" className="rounded border p-2" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder={preview.confirmation_phrase}/><button className="rounded bg-red-700 px-3 py-2 text-white" onClick={() => void execute()}>{mode === "confirm" ? "Подтвердить происхождение" : "Удалить один приказ"}</button></> : <div className="font-medium text-red-700">Операция заблокирована.</div>}</div> : null}
    {batch ? <div className="space-y-2 rounded border border-amber-400 p-3"><h3>Batch preview</h3><div>Готовы: {batch.ready.map((item) => item.order_id).join(", ") || "нет"}</div><div>Заблокированы: {batch.blocked.map((item) => `${item.order_id}: ${item.reason}`).join(", ") || "нет"}</div><button onClick={() => setSelectedIds((ids) => ids.filter((id) => !batch.blocked.some((item) => item.order_id === id) && !batch.legacy.some((item) => item.order_id === id)))}>Исключить заблокированные</button>{batch.can_execute ? <><input aria-label="Причина batch-операции" value={reason} onChange={(e) => setReason(e.target.value)} /><input aria-label="Фраза batch-подтверждения" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder={batch.confirmation_phrase}/><button className="rounded bg-red-700 px-3 py-2 text-white" onClick={() => void batchExecute()}>Подтвердить batch-удаление</button></> : null}</div> : null}
    {message ? <p role="status">{message}</p> : null}
  </section>;
}
