"use client";
import { useState } from "react";
import { apiFetchJson } from "@/lib/api";
type Classification = "CONFIRMED_TECHNICAL" | "LEGACY_TECHNICAL_CANDIDATE" | "REGULAR";
type Order = { order_id: number; order_number?: string | null; order_date?: string | null; order_type_code: string; status: string; employees?: string[]; classification: Classification };
type Preview = { classification: Classification; can_delete: boolean; can_confirm_provenance?: boolean; confirmation_phrase: string; planned_deletions: { table: string; count: number }[]; blocking_dependencies: { table: string; count: number }[] };
export default function TechnicalPersonnelOrdersPanel() {
  const [query, setQuery] = useState(""); const [field, setField] = useState("q"); const [items, setItems] = useState<Order[]>([]); const [preview, setPreview] = useState<Preview | null>(null); const [selected, setSelected] = useState<Order | null>(null); const [mode, setMode] = useState<"delete" | "confirm">("delete"); const [reason, setReason] = useState(""); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState("");
  function showError(error: unknown) { setMessage(error instanceof Error ? error.message : "Не удалось выполнить операцию."); }
  async function search() { setMessage(""); setPreview(null); try { const response = await apiFetchJson(`/directory/technical-personnel-order-cleanup/search?${field}=${encodeURIComponent(query)}`) as { items: Order[] }; setItems(response.items); } catch (error) { showError(error); } }
  async function inspect(order: Order, nextMode: "delete" | "confirm") { setMessage(""); try { setSelected(order); setMode(nextMode); setPreview(await apiFetchJson(`/directory/technical-personnel-order-cleanup/${order.order_id}/${nextMode === "confirm" ? "provenance-preview" : "preview"}`) as Preview); } catch (error) { showError(error); } }
  async function execute() { if (!selected || !reason.trim() || confirmation !== preview?.confirmation_phrase) { setMessage("Укажите причину и точную фразу подтверждения."); return; } try { const endpoint = mode === "confirm" ? "confirm-provenance" : "execute"; const result = await apiFetchJson(`/directory/technical-personnel-order-cleanup/${selected.order_id}/${endpoint}`, { method: "POST", body: JSON.stringify({ reason, confirmation_phrase: confirmation }) }) as { status: string }; setMessage(`${mode === "confirm" ? "Происхождение подтверждено" : "Удаление завершено"}: ${result.status}`); await search(); } catch (error) { showError(error); } }
  return <section className="space-y-3" aria-label="Технические кадровые приказы"><p className="text-sm text-zinc-600 dark:text-zinc-400">Legacy-кандидаты можно только проверить и отдельно подтвердить. Массовое удаление недоступно.</p><div className="flex gap-2"><select aria-label="Поле поиска технического приказа" className="rounded border p-2" value={field} onChange={(e) => setField(e.target.value)}><option value="order_id">Точный order_id</option><option value="q">Номер приказа</option><option value="employee_name">ФИО сотрудника</option><option value="import_source">Источник импорта</option></select><input aria-label="Поиск технического приказа" className="rounded border p-2" value={query} onChange={(e) => setQuery(e.target.value)} /><button className="rounded bg-blue-600 px-3 py-2 text-white" onClick={search}>Найти</button></div>{items.map((order) => <div className="rounded border p-3" key={order.order_id}><div>#{order.order_id} · {order.order_number || "без номера"} · {order.order_date || "без даты"}</div><div className="text-sm">{order.order_type_code} · {order.status} · {order.classification} · {(order.employees || []).join(", ")}</div><button className="mt-2 rounded border px-2 py-1" onClick={() => inspect(order, "delete")}>Preview удаления</button>{order.classification === "LEGACY_TECHNICAL_CANDIDATE" ? <button className="ml-2 mt-2 rounded border px-2 py-1" onClick={() => inspect(order, "confirm")}>Подтвердить техническое происхождение</button> : null}</div>)}{preview && selected ? <div className="space-y-2 rounded border border-amber-400 p-3"><h3 className="font-semibold">Preview #{selected.order_id}</h3><div>Класс: {preview.classification}</div><div>Удалятся: {preview.planned_deletions.map((x) => `${x.table} (${x.count})`).join(", ")}</div><div>Блокеры: {preview.blocking_dependencies.length ? preview.blocking_dependencies.map((x) => `${x.table} (${x.count})`).join(", ") : "нет"}</div>{(mode === "confirm" ? preview.can_confirm_provenance : preview.can_delete) ? <><input aria-label="Причина операции" className="rounded border p-2" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Причина"/><input aria-label="Фраза подтверждения" className="rounded border p-2" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} placeholder={preview.confirmation_phrase}/><button className="rounded bg-red-700 px-3 py-2 text-white" onClick={execute}>{mode === "confirm" ? "Подтвердить происхождение" : "Удалить один приказ"}</button></> : <div className="font-medium text-red-700">Операция заблокирована.</div>}</div> : null}{message ? <p role="status">{message}</p> : null}</section>;
}
